Talend/component-runtime

- component-form/component-form-demo/src/main/frontend/package.json
- component-runtime-beam/src/main/java/org/talend/components/runtime/beam/impl/VolatilePipelineOptions.java
- component-runtime-impl/src/main/java/org/talend/components/runtime/internationalization/InternationalizationServiceFactory.java
- component-runtime-manager/src/test/java/org/talend/components/runtime/manager/service/ResolverImplTest.java
- component-runtime-testing/component-runtime-testing-spark/src/main/java/org/talend/components/runtime/testing/spark/SparkClusterRule.java
- talend-component-maven-plugin/src/main/java/org/talend/components/maven/OldTComponentBridgeMojo.java
* Fix tests
* Fix maven filename for windows
Build failed on Windows OS before the changes were made
PR adds fixes for builds on windows OS
> fix: fix build issues for windows os

- container/container-core/src/test/java/org/talend/component/ContainerManagerTest.java
- container/container-core/src/test/java/org/talend/component/ContainerTest.java
Package name was wrong
Fix package name in test classes
> fix: change package name to component

- component-server/pom.xml
- component-studio-integration/pom.xml
- component-studio-integration/src/build/StudioDependencies.groovy
- component-studio-integration/src/main/java-templates/org/talend/component/studio/GAV.java
- component-studio-integration/src/main/java-templates/org/talend/component/studio/ServerManager.java
- component-studio-integration/src/main/java/org/talend/component/studio/ProcessManager.java
- component-studio-integration/src/main/java/org/talend/component/studio/ServerManager.java
- component-studio-integration/src/test/java/org/talend/component/studio/ServerManagerTest.java
- pom.xml
Task of preparation for the studio integration.
Starts the web server from the studio to be able to integrate it like the web side.
> start server with studio

- documentation/pom.xml
* Fix path to sample component
> fix: fix path for documentation

- component-server/pom.xml
- component-server/src/main/java/org/talend/sdk/component/server/configuration/WebSocketBroadcastSetup.java
- component-server/src/test/java/org/talend/sdk/component/server/front/ActionResourceTest.java
- component-server/src/test/java/org/talend/sdk/component/server/front/ComponentResourceTest.java
- component-server/src/test/java/org/talend/sdk/component/server/front/ExecutionResourceTest.java
- component-server/src/test/java/org/talend/sdk/component/server/test/websocket/WebsocketClient.java
- pom.xml
Basic prototype of a websocket integration for the jaxrs layer.
> websocket transport jaxrs

- .gitignore
to simplify work in git when using Eclipse IDE
add eclipse settings for .gitignore file
> chore: add gitignore for eclipse

- documentation/src/main/jbake/content/extensions.adoc
- documentation/src/main/jbake/content/i18n-extension.adoc
- documentation/src/main/jbake/content/index.adoc
- i18n-loader/pom.xml
- i18n-loader/src/main/java/org/talend/sdk/component/i18n/BaseBundle.java
- i18n-loader/src/main/java/org/talend/sdk/component/i18n/BaseControl.java
- i18n-loader/src/main/java/org/talend/sdk/component/i18n/BaseProvider.java
- i18n-loader/src/main/java/org/talend/sdk/component/i18n/ComponentResourceBundleControlProvider.java
- i18n-loader/src/main/java/org/talend/sdk/component/i18n/MapBundle.java
- i18n-loader/src/main/java/org/talend/sdk/component/i18n/ProviderLocator.java
- i18n-loader/src/main/resources/META-INF/services/java.util.spi.ResourceBundleControlProvider
- i18n-loader/src/test/java/org/talend/sdk/component/i18n/ComponentResourceBundleControlProviderTest.java
- pom.xml
An i18n-extension to load resource bundle from custom location/logic
> i18n-loader

- component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/model/ComponentIndices.java
- component-studio-integration/pom.xml
- component-studio-integration/src/build/StudioDependencies.groovy
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/Lookups.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ProcessManager.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ServerManager.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/TaCoKitGenericProvider.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/lang/Pair.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/MetadataContentProvider.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/NodeActionProvider.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/WizardRegistry.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/service/ComponentService.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/websocket/WebSocketClient.java
- component-studio-integration/src/main/resources/plugin.xml
- component-studio-integration/src/test/java/org/talend/sdk/component/studio/ServerManagerTest.java
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/ValidateComponentMojo.java
pushing eagerly to share some code, not yet ready otherwise
> preparing the metadata support into the studio

- component-studio-integration/pom.xml
- component-studio-integration/src/build/Icons.groovy
- pom.xml
- talend-component-maven-plugin/pom.xml
ensuring png icons are bundle in studio integration
> ensuring png icons are bundle in studio integration

- component-runtime-testing/component-runtime-testing-spark/src/main/java/org/talend/sdk/component/runtime/testing/spark/SparkClusterRule.java
trying to install winutils under windows
> trying to install winutils under windows

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/xbean/KnownJarsFilter.java
- component-server/pom.xml
- component-server/src/main/java/org/talend/sdk/component/server/configuration/ComponentServerConfiguration.java
- component-server/src/main/java/org/talend/sdk/component/server/front/error/DefaultExceptionHandler.java
- component-server/src/main/java/org/talend/sdk/component/server/front/model/ErrorDictionary.java
- component-server/src/main/java/org/talend/sdk/component/server/front/monitoring/BraveConfiguration.java
- component-server/src/main/java/org/talend/sdk/component/server/front/monitoring/BraveFeature.java
- component-server/src/main/java/org/talend/sdk/component/server/front/swagger/DocumentationToggle.java
- component-server/src/main/java/org/talend/sdk/component/server/lang/StringPropertiesTokenizer.java
- component-server/src/main/java/org/talend/sdk/component/server/service/PoolProducer.java
> brave support

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
> fix find components configuration

- .travis.yml
- documentation/src/main/jbake/content/documentation.adoc
- talend-component-maven-plugin/src/it/failure-action/src/main/java/org/superbiz/package-info.java
- talend-component-maven-plugin/src/it/failure-datastore/src/main/java/org/superbiz/package-info.java
- talend-component-maven-plugin/src/it/failure-family/invoker.properties
- talend-component-maven-plugin/src/it/failure-family/pom.xml
- talend-component-maven-plugin/src/it/failure-family/src/main/java/org/superbiz/MyComponent.java
- talend-component-maven-plugin/src/it/failure-family/src/main/java/org/superbiz/package-info.java
- talend-component-maven-plugin/src/it/failure-family/src/main/resources/org/superbiz/Messages.properties
- talend-component-maven-plugin/src/it/failure-i18n-custom/src/main/java/org/superbiz/package-info.java
- talend-component-maven-plugin/src/it/failure-i18n-missing/src/main/java/org/superbiz/package-info.java
- talend-component-maven-plugin/src/it/failure-i18n/src/main/java/org/superbiz/package-info.java
- talend-component-maven-plugin/src/it/failure-missing-icon/src/main/java/org/superbiz/package-info.java
- talend-component-maven-plugin/src/it/failure-missing-version/src/main/java/org/superbiz/package-info.java
- talend-component-maven-plugin/src/it/failure-serialization/src/main/java/org/superbiz/package-info.java
- talend-component-maven-plugin/src/it/generator/src/main/java/org/talend/test/package-info.java
- talend-component-maven-plugin/src/it/success-datastore/src/main/java/org/superbiz/package-info.java
- talend-component-maven-plugin/src/it/tcomp0-bridge/src/main/java/org/superbiz/package-info.java
- talend-component-maven-plugin/src/it/valid/src/main/java/org/superbiz/package-info.java
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/ValidateComponentMojo.java
validating that families have @Icon. This implementation is a simple one (we actually use the same logic than for @Components to find @Icon on a package instead of checking it on the same package) but should be good enough to start
> validating each family has an icon

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ProcessManager.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ServerManager.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/websocket/WebSocketClient.java
enhancing the healthcheck to avoid a loop issue and an eager exit condition
> enhancing the healthcheck to avoid a loop issue and an eager exit condition

- documentation/src/main/jbake/content/documentation.adoc
> feature(TCOMP-650): enrich documentation

- documentation/src/main/jbake/content/documentation.adoc
the doc also provide a simple example
provide doc
amend the doc with an explanation for the configuration type index
> amend the doc with an explanation for the configuration type index

- component-server/pom.xml
- component-starter-server/pom.xml
- documentation/src/main/jbake/content/documentation-rest.adoc
> logging documentation

- component-studio-integration/pom.xml
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
- component-studio-integration/src/test/java/org/talend/sdk/component/studio/ComponentModelTest.java
> chore: change studio dependencies version to 7.0.1-M1

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/reflect/ParameterModelService.java
- component-runtime-testing/component-runtime-junit/pom.xml
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/SimpleFactory.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/junit/SimpleFactoryTest.java
- component-runtime-testing/component-runtime-junit/src/test/resources/log4j2.xml
- documentation/src/main/jbake/content/documentation-testing.adoc
> adding SimpleFactory

- README.adoc
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/output/ProcessorImpl.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/visitor/ModelVisitor.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/reflect/ParameterModelService.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/AutoChunkProcessor.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/ControllableInputFactory.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/JoinInputFactory.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/MainInputFactory.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/SimpleComponentRule.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/SimpleFactory.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/junit/SimpleComponentRuleTest.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/junit/component/Source.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/junit/component/Transform.java
- documentation/src/main/jbake/content/documentation-testing.adoc
basic testing stack for unitary tests
> basic testing stack for unitary tests

- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/json/JsonbProducer.java
- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/statistic/StatisticService.java
- component-starter-server/src/test/resources/log4j2.xml
logging stats as json in starter webapp
> [TCOMP-684] logging stats as json

- component-server/pom.xml
- component-server/src/main/java/org/talend/sdk/component/server/front/ActionResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/ConfigurationTypeResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/ExecutionResource.java
adding documentation on our endpoints and integrating it into the adoc
> adding documentation on our endpoints and integrating it into the adoc

- component-starter-server/src/main/frontend/src/Component/AppButton.js
- component-starter-server/src/main/frontend/src/Component/AppButton.scss
- component-starter-server/src/main/frontend/src/Component/Help.js
- component-starter-server/src/main/frontend/src/Component/Help.scss
- component-starter-server/src/main/frontend/src/Component/Schema.js
- component-starter-server/src/main/frontend/src/Generator/Component.js
- component-starter-server/src/main/frontend/src/Generator/FacetSelector.js
- component-starter-server/src/main/frontend/src/Generator/FacetSelector.scss
- component-starter-server/src/main/frontend/src/Generator/Generator.js
- component-starter-server/src/main/frontend/src/Generator/Mapper.js
- component-starter-server/src/main/frontend/src/Generator/Processor.js
- component-starter-server/src/main/frontend/src/Generator/ProjectMetadata.js
adding contextual help everywhere in the starter
> adding contextual help everywhere in the starter

- documentation/src/main/jbake/content/documentation.adoc
> fix: fix documentation

- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/configuration/ConfigurationConverters.java
- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/configuration/StarterConfiguration.java
- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/facet/component/ComponentGenerator.java
- component-starter-server/src/main/resources/generator/component/Configuration.mustache
- component-starter-server/src/test/java/org/talend/sdk/component/starter/server/service/facet/component/ComponentGeneratorConfigurationTest.java
- component-starter-server/src/test/java/org/talend/sdk/component/starter/server/service/facet/component/ComponentGeneratorTest.java
- component-starter-server/src/test/resources/generated/ComponentGeneratorTest/configurationWithCredential/CredentialConfiguration.java
- component-starter-server/src/test/resources/generated/ComponentGeneratorTest/configurationWithCredential/TProcOutputConfiguration.java
> generate @Credential when a credential name is used in the conf class

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/BaseProcessorFn.java
support of multiple inputs from the same branch
> better handling of BeamInputFactory

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/websocket/WebSocketClient.java
- component-studio-integration/src/test/java/org/talend/sdk/component/studio/ServerManagerTest.java
adding config type client call in the studio integration
> adding config type client call in the studio integration

- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/facet/component/ComponentGenerator.java
- component-starter-server/src/main/resources/generator/component/Processor.mustache
- component-starter-server/src/test/java/org/talend/sdk/component/starter/server/service/facet/component/ComponentGeneratorTest.java
- component-starter-server/src/test/resources/generated/ComponentGeneratorTest/processorGenericInput/TProcProcessor.java
- component-starter-server/src/test/resources/generated/ComponentGeneratorTest/processorGenericOutput/TProcProcessor.java
- component-starter-server/src/test/resources/generated/ComponentGeneratorTest/processorInput/TProcProcessor.java
- component-starter-server/src/test/resources/generated/ComponentGeneratorTest/processorOutput/TProcProcessor.java
- component-starter-server/src/test/resources/generated/ComponentGeneratorTest/standardProcessor/TProcProcessor.java
> sort Input and Output and ignore the default name for branches in Prcessors

- component-server/src/main/java/org/talend/sdk/component/server/front/ConfigurationTypeResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/model/ConfigTypeNode.java
- component-server/src/test/java/org/talend/sdk/component/server/front/ComponentResourceTest.java
- component-server/src/test/java/org/talend/sdk/component/server/front/ConfigurationTypeResourceTest.java
- component-server/src/test/java/org/talend/sdk/component/server/test/InitTestInfra.java
- component-server/src/test/java/org/talend/sdk/component/server/test/jdbc/JdbcInput.java
fixing the config tree endpoint to have right edges
> fixing the config tree endpoint to have right edges

- .travis.yml
- .travis/settings.xml
- documentation/pom.xml
- documentation/src/build/GithubPages.groovy
- documentation/src/main/jbake/templates/menu.gsp
adding latest website deployment and versions menu
> adding latest website deployment and versions menu

- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/facet/travis/TravisFacet.java
- component-starter-server/src/test/java/org/talend/sdk/component/starter/server/front/ProjectResourceTest.java
> adding travis facet

- component-runtime-design-extension/src/test/java/org/talend/sdk/component/design/extension/repository/RepositoryModelBuilderTest.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/ResolverImpl.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/asm/PluginGenerator.java
- component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/model/Dependencies.java
- component-server/src/main/java/org/talend/sdk/component/server/front/model/DependencyDefinition.java
- component-server/src/main/java/org/talend/sdk/component/server/service/ComponentManagerService.java
- component-server/src/test/java/org/talend/sdk/component/server/front/ComponentResourceTest.java
- component-server/src/test/java/org/talend/sdk/component/server/test/InitTestInfra.java
- container/container-core/src/main/java/org/talend/sdk/component/container/Container.java
- container/container-core/src/main/java/org/talend/sdk/component/container/ContainerManager.java
- container/container-core/src/main/java/org/talend/sdk/component/dependencies/maven/Artifact.java
- container/container-core/src/main/java/org/talend/sdk/component/dependencies/maven/MvnCoordinateToFileConverter.java
- container/container-core/src/main/java/org/talend/sdk/component/dependencies/maven/MvnDependencyListLocalRepositoryResolver.java
- container/container-core/src/test/java/org/talend/sdk/component/ContainerTest.java
- container/container-core/src/test/java/org/talend/sdk/component/dependencies/maven/ArtifactTest.java
- container/container-core/src/test/java/org/talend/sdk/component/dependencies/maven/MvnDependencyListLocalRepositoryResolverTest.java
- container/container-core/src/test/java/org/talend/sdk/component/jmx/JmxManagerTest.java
> adding dependencies endpoints

- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/SimpleComponentRule.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/lang/StreamDecorator.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/junit/SimpleComponentRuleTest.java
> parallel testing for mappers

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyTypes.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/WidgetTypeMapper.java
fixes Closed_List support (it uses real Enum values)
> feat(TCOMP-681): fix support for Closed List

- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/SimpleComponentRule.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/SimpleFactory.java
- component-server/src/main/java/org/talend/sdk/component/server/front/ActionResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/ConfigurationTypeResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/model/SimplePropertyDefinition.java
- component-server/src/main/java/org/talend/sdk/component/server/service/PropertiesService.java
- component-server/src/test/java/org/talend/sdk/component/server/front/ComponentResourceTest.java
adding default values for properties
> adding default values for properties

- component-server/pom.xml
- component-server/src/main/java/org/talend/sdk/component/server/configuration/ScmConfigurationLoader.java
- component-server/src/main/java/org/talend/sdk/component/server/front/EnvironmentResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/model/Environment.java
- component-server/src/test/java/org/talend/sdk/component/server/front/EnvironmentResourceTest.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ProcessManager.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/websocket/WebSocketClient.java
- pom.xml
goal is to have an endpoint which can be used to validate which version is deployed/called by a client
> environment endpoint to know which version we are relying on as a client

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/reflect/Constructors.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/reflect/ParameterModelService.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/tools/AsciidocDocumentationGenerator.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/tools/BaseTask.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/tools/ComponentValidator.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/tools/DefaultValueInspector.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/tools/Log.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/tools/ReflectiveLog.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/tools/AsciidocDocumentationGeneratorTest.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/tools/ComponentValidatorTest.java
- component-runtime-manager/src/test/java/org/talend/test/valid/MyComponent.java
- component-server/src/main/java/org/talend/sdk/component/server/service/PropertiesService.java
- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/build/MavenBuildGenerator.java
- documentation/src/main/jbake/content/documentation.adoc
- gradle-talend-component/src/main/java-templates/org/talend/sdk/component/gradle/TaCoKitExtension.java
- gradle-talend-component/src/main/java/org/talend/sdk/component/gradle/DocumentationTask.java
- gradle-talend-component/src/main/java/org/talend/sdk/component/gradle/TaCoKitPlugin.java
- gradle-talend-component/src/main/java/org/talend/sdk/component/gradle/TaCoKitTask.java
- gradle-talend-component/src/main/java/org/talend/sdk/component/gradle/ValidateTask.java
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/AsciidocMojo.java
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/ValidateComponentMojo.java
documentation mojo from the component model
> adding documentation task/mojo

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/tools/ComponentValidator.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/tools/ComponentValidatorTest.java
- component-runtime-manager/src/test/java/org/talend/test/failure/datastore/MyDataStore2.java
- component-runtime-manager/src/test/java/org/talend/test/valid/datastore/MyDataStore2.java
> validate datastore with checkable for healthcheck

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/tools/Log.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/tools/ReflectiveLog.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/tools/StudioInstaller.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/tools/ComponentValidatorTest.java
- component-server/src/main/java/org/talend/sdk/component/server/configuration/ComponentServerConfiguration.java
- component-server/src/main/java/org/talend/sdk/component/server/configuration/WebSocketBroadcastSetup.java
- component-server/src/main/java/org/talend/sdk/component/server/front/security/CommandSecurityProvider.java
- component-server/src/main/java/org/talend/sdk/component/server/front/security/ConnectionSecurityProvider.java
- component-server/src/main/java/org/talend/sdk/component/server/service/ComponentManagerService.java
- component-server/src/main/java/org/talend/sdk/component/server/service/security/NoopHandler.java
- component-server/src/main/java/org/talend/sdk/component/server/service/security/SecurityExtension.java
- component-server/src/main/java/org/talend/sdk/component/server/service/security/event/OnCommand.java
- component-server/src/main/java/org/talend/sdk/component/server/service/security/event/OnConnection.java
- component-server/src/main/java/org/talend/sdk/component/server/service/security/event/ValidableEvent.java
- component-server/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
- component-server/src/test/java/org/talend/sdk/component/server/test/InitTestInfra.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ProcessManager.java
- gradle-talend-component/src/main/java-templates/org/talend/sdk/component/gradle/TaCoKitExtension.java
- gradle-talend-component/src/main/java/org/talend/sdk/component/gradle/DeployInStudioTask.java
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/DeployStudioMojo.java
> basic security backbone - no impl - and studio deployment task

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/reflect/ParameterModelService.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/tools/ComponentValidator.java
- component-runtime-manager/src/test/java/org/talend/test/valid/datastore/MyDataStore2.java
- component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResource.java
> fix some bugs in components metadata

- component-server/src/main/java/org/talend/sdk/component/server/configuration/ComponentServerConfiguration.java
- component-server/src/main/java/org/talend/sdk/component/server/front/monitoring/BraveConfiguration.java
> tracing auto configuration

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/reflect/ParameterModelService.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/ParameterModelServiceTest.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/test/MethodsHolder.java
avoid to duplicate actions for lists
> avoid to duplicate actions for lists

- component-studio-integration/pom.xml
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/TemplatesExtractor.java
- component-studio-integration/src/test/java/org/talend/sdk/component/studio/ComponentModelTest.java
* Add dependencies to ComponentModel
* Include dependencies file to jar
> feature(TCOMP-683): runtime integration

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/model/ComponentId.java
- component-server/src/main/java/org/talend/sdk/component/server/service/ComponentManagerService.java
- component-server/src/test/java/org/talend/sdk/component/server/front/ComponentResourceTest.java
- component-studio-integration/src/test/java/org/talend/sdk/component/studio/ComponentModelTest.java
adding gav in componentId
it is important to let clients using another provisioning solution.
> adding gav in componentId

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/internationalization/ComponentBundle.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/internationalization/InternalBundle.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/internationalization/ParameterBundle.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ParameterMeta.java
- component-server/src/main/java/org/talend/sdk/component/server/configuration/ComponentServerConfiguration.java
- component-server/src/main/java/org/talend/sdk/component/server/front/error/DefaultExceptionHandler.java
- component-server/src/main/java/org/talend/sdk/component/server/service/PropertiesService.java
- component-server/src/test/java/org/talend/sdk/component/server/service/PropertiesServiceTest.java
- component-server/src/test/resources/org/talend/sdk/component/server/service/Messages.properties
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ProcessManager.java
> translate config using Class Name

- documentation/src/main/jbake/content/documentation.adoc
> (doc): translatable configuration using the config class name

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/ITaCoKitElementParameterEventProperties.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/TaCoKitElementParameter.java
https://jira.talendforge.org/browse/TCOMP-691
Add TaCoKitElementParameter
> task(TCOMP-691): create context menu for Tacokit node in repository panel

- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/facet/component/ComponentGenerator.java
- component-starter-server/src/main/resources/generator/component/Processor.mustache
- component-starter-server/src/test/java/org/talend/sdk/component/starter/server/service/facet/component/ComponentGeneratorTest.java
- component-starter-server/src/test/resources/generated/ComponentGeneratorTest/standardProcessor/TProcProcessor.java
> fix processor with multiples in/out generation

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-server/src/main/java/org/talend/sdk/component/server/dao/ComponentActionDao.java
- component-server/src/main/java/org/talend/sdk/component/server/dao/ComponentDao.java
- component-server/src/main/java/org/talend/sdk/component/server/dao/ComponentFamilyDao.java
- component-server/src/main/java/org/talend/sdk/component/server/front/ActionResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResource.java
- component-server/src/main/java/org/talend/sdk/component/server/service/ComponentManagerService.java
- component-server/src/test/java/org/talend/sdk/component/server/service/ComponentManagerServiceTest.java
- container/container-core/src/main/java/org/talend/sdk/component/container/ContainerManager.java
> add deploy undeploy to component service

- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/SimpleFactory.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/junit/SimpleFactoryTest.java
> add support of list of object and list with nested lists

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitConfigurationWizardPage.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/WizardSettingsCreator.java
quick fix for password display issue
> fix(TCOMP-681): quick fix for password display issue

- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImplTest.java
> for issue "no private access for invokespecial"

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImpl.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImplTest.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/ExceptionVerifier.java
> add error handling to http client

- component-server/pom.xml
- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/template/TemplateRenderer.java
- pom.xml
> fix pom & starter tests on win

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/Metadatas.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SchemaSettingsCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/WidgetTypeMapper.java
- component-studio-integration/src/main/resources/jet_stub/generic/configuration.javajet
* Add schema handling to runtime
> feat(TCOMP-683): add schema

- component-studio-integration/src/main/resources/jet_stub/generic/configuration.javajet
> feat(TCOMP-683): support default values in tables

- component-studio-integration/src/main/resources/components/tTaCoKitGuessSchema/TaCoKitGuessSchema.javajet
https://jira.talendforge.org/browse/TCOMP-682
Potential NPE bug and missing some columns bug
> task(TCOMP-682): Metadata integration

- component-runtime-testing/component-runtime-http-junit/src/main/java/org/talend/sdk/component/junit/http/internal/impl/PassthroughHandler.java
> copy request to use in a separated thread

- pom.xml
> add extenstion to get mojo execution time

- .travis.yml
- .travis/install.sh
use travis stages to make build task parallel
> Use stages in travis build

- .travis.yml
> add install phase to all stages

- .travis.yml
> fix deploy documentation stage

- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/api/ClientFactory.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/api/UiSpecService.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/PropertyContext.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/PropertyConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/JsonSchemaConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/UiPropertiesConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/UiSchemaConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/schema/ArrayPropertyConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/schema/EnumPropertyConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/AbstractWidgetConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/CodeWidgetConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/CredentialWidgetConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/DataListWidgetConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/FieldSetWidgetConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/MultiSelectTagWidgetConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/NumberWidgetConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/TextWidgetConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/ToggleWidgetConverter.java
- component-form/component-form-core/src/test/java/org/talend/sdk/component/form/api/UiSpecServiceTest.java
- component-form/component-form-demo/src/main/java/org/talend/sdk/component/form/demo/DemoConfiguration.java
> refactor form core

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SchemaSettingsCreator.java
> fix add schema widget

- component-studio-integration/pom.xml
- component-studio-integration/src/build/StudioDependencies.groovy
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/TaCoKitCache.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitRepositoryContentHandler.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitTypeProcessor.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyDefinitionDecorator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
add support for repository value
> feat(TCOMP-681): implement repository value support

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/model/ComponentModelSpy.java
- component-studio-integration/src/main/resources/components/tTaCoKitGuessSchema/TaCoKitGuessSchema.javajet
> Fix a compile error and a potential guess schema bug

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- component-studio-integration/src/main/resources/jet_stub/generic/input/input_begin.javajet
- component-studio-integration/src/main/resources/jet_stub/generic/processor/processor_main.javajet
> fix record mapping in javajet

- component-studio-integration/src/main/resources/jet_stub/generic/configuration.javajet
* Fix error in configuration.javajet
> feature(TCOMP-683): guess schema

- component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResource.java
- component-server/src/test/java/org/talend/sdk/component/server/front/ComponentResourceTest.java
- component-server/src/test/java/org/talend/sdk/component/server/test/ComponentClient.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/websocket/WebSocketClient.java
> deactivate include icon in index resource by default

- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/AbstractWidgetConverter.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/internationalization/ParameterBundle.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ParameterMeta.java
- component-server/src/main/java/org/talend/sdk/component/server/front/model/SimplePropertyDefinition.java
- component-server/src/main/java/org/talend/sdk/component/server/service/PropertiesService.java
- component-server/src/test/java/org/talend/sdk/component/server/service/PropertiesServiceTest.java
- component-server/src/test/resources/org/talend/sdk/component/server/service/Messages.properties
- component-studio-integration/pom.xml
- component-studio-integration/src/build/StudioDependencies.groovy
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyDefinitionDecorator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TextElementParameter.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitConfigurationWizardPage.java
- documentation/src/main/jbake/content/documentation.adoc
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/LegacyComponentBridgeMojo.java
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/OldTComponentBridgeMojo.java
> add support to placeholders to the component model

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/Lookups.java
> use old cache

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/output/data/ObjectMapImpl.java
> fix objectMapImpl when objectmap is wrapped in a pojo

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/CodecMatcher.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImpl.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/CodecMatcherTest.java
> add content-type support to http service for codec

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImpl.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/ReflectionServiceTest.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImplTest.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/BaseComponentsHandler.java
- documentation/src/main/jbake/content/documentation.adoc
> Service injection in codec

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/AbstractConnectorCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/OutputConnectorCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/ProcessorConnectorCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
- component-studio-integration/src/main/resources/jet_stub/generic/processor/processor_main.javajet
* Add reject flow to connectors list
* Add schemas for all connectors, which need this
* Fix generic in javajet
> fix: fix reject flow

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImpl.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImplTest.java
> Support jaxb codec by default

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImpl.java
> fix supported codec validation

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/TaCoKitCache.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
fix NPE in case component has no ConfigTypeNode
> fix(TCOMP-681): fix NPE when component has no ConfigType

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/AbstractConnectorCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/GuessSchema.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/TaCoKitGuessSchemaProcess.java
* Fixed removal of node output connectors
* Fixed impossibility of schema setting after guess schema process
> fix: fix guess schema process

- component-studio-integration/src/test/java/org/talend/sdk/component/studio/ComponentModelTest.java
* Change number of dependencies
> fix: fix ComponentModelTest

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/chain/ChainedInput.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/chain/ChainedMapper.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/chain/ExecutionChain.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
- component-studio-integration/src/main/resources/jet_stub/generic/input/input_begin.javajet
- component-studio-integration/src/main/resources/jet_stub/generic/processor/processor_main.javajet
* Extract ChainedInput and ChainedMapper classes
* Fix input javajet
* Set data autopropagation to false in ComponentModel
* Fix processor javajet
> fix: split mappers

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/CodecMatcher.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImpl.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/MediaTypeComparator.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/CodecMatcherTest.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/MediaTypeComparatorTest.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/InputFactoryIterable.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/JoinInputFactory.java
> fix codec ordder dropping objectmap

- component-studio-integration/src/main/resources/jet_stub/generic/input/input_begin.javajet
- component-studio-integration/src/main/resources/jet_stub/generic/processor/processor_begin.javajet
- component-studio-integration/src/main/resources/jet_stub/generic/processor/processor_main.javajet
> fix: fix javajets after ObjectMap removal

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/coder/JsonpJsonObjectCoder.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/input/PartitionMapperImpl.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/proxy/JavaProxyEnricherFactory.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/proxy/SerializationHandlerReplacer.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImpl.java
> fix proxy serialization

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyTreeCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
fix "required parameter is empty" issue
> fix(TCOMP-681): fix required parameter issue

- component-starter-server/src/main/resources/generator/facet/beam/BeamProcessorTest.mustache
- component-starter-server/src/test/resources/generated/ProjectResourceTest/beamFacet/TInOutputBeamTest.java
- component-starter-server/src/test/resources/generated/ProjectResourceTest/beamFacetProcessorOutput/TInProcessorBeamTest.java
> add waitUntilFinish to generated beam test

- component-tools/src/main/java/org/talend/sdk/component/tools/ComponentValidator.java
- component-tools/src/test/java/org/talend/sdk/component/tools/ComponentValidatorTest.java
- component-tools/src/test/java/org/talend/test/failure/layout/MyComponent.java
- component-tools/src/test/java/org/talend/test/failure/layout/package-info.java
- component-tools/src/test/resources/org/talend/test/failure/layout/Messages.properties
- gradle-talend-component/src/main/java-templates/org/talend/sdk/component/gradle/TaCoKitExtension.java
- gradle-talend-component/src/main/java/org/talend/sdk/component/gradle/ValidateTask.java
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/ValidateComponentMojo.java
> validate layout declaration

- component-runtime-testing/component-runtime-beam-junit/pom.xml
- component-runtime-testing/component-runtime-beam-junit/src/test/java/org/talend/sdk/component/junit/beam/ProcessorTest.java
- component-runtime-testing/pom.xml
> add new module structure component runtime beam junit

- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/BaseIOHandler.java
- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/InputsHandler.java
- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/OutputsHandler.java
- component-studio-integration/src/main/resources/jet_stub/generic/processor/processor_begin.javajet
- component-studio-integration/src/main/resources/jet_stub/generic/processor/processor_main.javajet
> fix processor javajets after moving code to java

- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/BaseIOHandler.java
- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/InputsHandler.java
- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/OutputsHandler.java
- component-studio-integration/src/main/resources/jet_stub/generic/processor/processor_begin.javajet
- component-studio-integration/src/main/resources/jet_stub/generic/processor/processor_main.javajet
> fix processing of input and output rows

- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/coder/JsonRoundTripTest.java
- component-runtime-testing/component-runtime-beam-junit/src/main/java/org/talend/sdk/component/junit/beam/Data.java
- component-runtime-testing/component-runtime-beam-junit/src/test/java/org/talend/sdk/component/junit/beam/ProcessorTest.java
- component-runtime-testing/component-runtime-beam-junit/src/test/java/org/talend/sdk/component/junit/beam/test/SampleProcessor.java
- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/facet/beam/BeamFacet.java
- component-starter-server/src/main/resources/generator/facet/beam/BeamProcessorTest.mustache
- component-starter-server/src/main/resources/generator/facet/beam/BeamSourceTest.mustache
- component-starter-server/src/test/resources/generated/ProjectResourceTest/beamFacet/TInMapperBeamTest.java
- component-starter-server/src/test/resources/generated/ProjectResourceTest/beamFacet/TInOutputBeamTest.java
- component-starter-server/src/test/resources/generated/ProjectResourceTest/beamFacetProcessorOutput/TInProcessorBeamTest.java
> fix beam test generation

- component-tools-webapp/src/main/frontend/package-template.json
- component-tools-webapp/src/main/frontend/webpack.config.js
> Fix js win

- component-tools/src/main/java/org/talend/sdk/component/tools/ComponentValidator.java
- component-tools/src/test/java/org/talend/sdk/component/tools/ComponentValidatorTest.java
- component-tools/src/test/java/org/talend/test/failure/layout/MyComponent.java
> validate config layout based on parameter meta

- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/UiSchemaConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/TextAreaWidgetConverter.java
> add textarea support in component form

- component-server/src/main/java/org/talend/sdk/component/server/service/httpurlconnection/IgnoreNetAuthenticatorInterceptor.java
- component-server/src/main/java/org/talend/sdk/component/server/service/httpurlconnection/NetAuthenticatorWorkaround.java
> ignore osgi authenticator on tacokit actions calls

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
fix ArrayOutOfBound exception for Schema property, when user switch to repository mode
> fix: fix Exception during switching to repository value

- component-tools/src/main/java/org/talend/sdk/component/tools/ComponentValidator.java
> skip layout validation when no layout is defined

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-server/src/main/java/org/talend/sdk/component/server/dao/ComponentActionDao.java
- component-server/src/main/java/org/talend/sdk/component/server/dao/ComponentDao.java
- component-server/src/main/java/org/talend/sdk/component/server/dao/ComponentFamilyDao.java
- component-server/src/main/java/org/talend/sdk/component/server/service/ComponentManagerService.java
- component-tools-webapp/src/main/java/org/talend/sdk/component/tools/webapp/AdminResource.java
- container/container-core/src/main/java/org/talend/sdk/component/container/Container.java
- container/container-core/src/main/java/org/talend/sdk/component/container/ContainerManager.java
- container/container-core/src/main/java/org/talend/sdk/component/jmx/ContainerMBean.java
- container/container-core/src/main/java/org/talend/sdk/component/jmx/JmxManager.java
- container/container-core/src/test/java/org/talend/sdk/component/jmx/JmxManagerTest.java
- container/container-core/src/test/java/org/talend/sdk/component/test/rule/TempJars.java
> fix reload component

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
> fix: fix schema visibility for component which has no Configuration

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/HealthCheckResolver.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyTreeCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/WidgetTypeMapper.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitConfigurationWizardPage.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/WizardTypeMapper.java
return password for wizard back
> fix: fix wizard password appearance

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java
- component-studio-integration/src/main/resources/messages.properties
> fix: return guess schema button back

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
> Show all possible schemas

- component-studio-integration/src/main/resources/jet_stub/generic/processor/processor_begin.javajet
- component-studio-integration/src/main/resources/jet_stub/generic/processor/processor_main.javajet
> Fix tcomp to tacokit connector name fetching

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/provider/TaCoKitMetadataContentProvider.java
fix Repository refresh after creating dataset/datastore
> fix: fix Metadata repository refresh issue

- documentation/pom.xml
- documentation/src/build/PrepareWebResources.groovy
- documentation/src/main/frontend/package-template.json
> fix the doc build under windows

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
makes schema label better, but doesn't handle all cases
> feat: make schema label better

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
> feat: add connector name to schema label

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java
> fix: fix NPE when component doesn't have properties

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java
> fix: override MultipleThreadDynamicComposite correctly

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/node/TaCoKitConfigurationRepositoryNode.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/node/TaCoKitFamilyRepositoryNode.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/provider/TaCoKitMetadataContentProvider.java
https://jira.talendforge.org/browse/TUP-19640
> task(TUP-19640): Deleted tacokit nodes can't be shown in recyclebin node

- documentation/src/main/antora/modules/ROOT/nav.adoc
- documentation/src/main/antora/modules/ROOT/pages/tutorial-create-an-input-component.adoc
> doc: add tutorial (Create an input component)

- documentation/src/main/antora/modules/ROOT/nav.adoc
- documentation/src/main/antora/modules/ROOT/pages/tutorial-create-an-input-component.adoc
- documentation/src/main/antora/modules/ROOT/pages/tutorial-generate-project-using-starter.adoc
- documentation/src/main/antora/modules/ROOT/pages/tutorial-test-your-components.adoc
> doc: add tutorial (test your components)

- documentation/src/main/antora/modules/ROOT/pages/tutorial-create-an-input-component.adoc
> doc: fix typo & add component family registration

- documentation/src/main/antora/modules/ROOT/nav.adoc
- documentation/src/main/antora/modules/ROOT/pages/tutorial-create-an-output-component.adoc
> chore: add tutorial for output

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImpl.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/HttpClientFactoryImplTest.java
> ignore null query params

- component-runtime-testing/component-runtime-http-junit/src/main/java/org/talend/sdk/component/junit/http/internal/impl/ServingProxyHandler.java
- component-runtime-testing/component-runtime-http-junit/src/test/java/org/talend/sdk/component/junit/http/junit4/JUnit4HttpApiTest.java
> add more expicit error when no reponse matching is found

- documentation/src/main/antora/modules/ROOT/pages/_partials/tutorials-index.adoc
- documentation/src/main/antora/modules/ROOT/pages/tutorial-create-components-rest-api.adoc
> add a tutorial on how to consume API in component

- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/maven/MavenDecrypter.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/maven/MavenDecrypterTest.java
- component-runtime-testing/component-runtime-junit/src/test/resources/maven/settings-empty.xml
- component-runtime-testing/component-runtime-junit/src/test/resources/maven/settings-security-empty.xml
- component-runtime-testing/component-runtime-junit/src/test/resources/maven/settings-security-null.xml
- component-runtime-testing/component-runtime-junit/src/test/resources/maven/settings-security.xml
- component-runtime-testing/component-runtime-junit/src/test/resources/maven/settings.xml
> fix mvn decrypter and add some tests

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/ModuleResolverTest.java
- container/container-core/src/main/java/org/talend/sdk/component/container/ContainerManager.java
> change error message when file is not found

- documentation/src/main/antora/modules/ROOT/pages/_partials/tutorials-index.adoc
- documentation/src/main/antora/modules/ROOT/pages/tutorial-test-rest-api.adoc
> tuto: how to test a component that consume a rest api

- documentation/src/main/antora/modules/ROOT/pages/tutorial-test-rest-api.adoc
> use toQueryString in the tuto

- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/JavaType.java
- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/JavaTypesManager.java
- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchema.java
to be merged with : https://github.com/Talend/tdi-studio-se/pull/2084
Test to be added in a separated PR.
> refactor guess schema class and fix gs by action

- build/NpmPublish.groovy
> fix npm publish script (readme & version)

- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchema.java
> fix: guess schema freeze

- component-server/src/main/java/org/talend/sdk/component/server/configuration/PropertiesSetup.java
- component-server/src/test/java/org/talend/sdk/component/server/test/ClientProducer.java
- component-server/src/test/java/org/talend/sdk/component/server/test/ComponentClient.java
> [TCOMP-751] activate content compression on component server

- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/facet/component/ComponentGenerator.java
- component-starter-server/src/test/resources/generated/ComponentGeneratorTest/sourceComplexConfiguration/SourceMessages.properties
> fix(TCOMP-775): fix configuration properties keys generation

- documentation/src/main/antora/modules/ROOT/pages/component-definition.adoc
> doc: add documentation for family and component icons

- talend-component-kit-intellij-plugin/src/main/resources/META-INF/plugin.xml
> fix(TCOMP-798): update intellij plugin change note

- talend-component-kit-intellij-plugin/src/main/java/org/talend/sdk/component/intellij/Configuration.java
- talend-component-kit-intellij-plugin/src/main/java/org/talend/sdk/component/intellij/module/ProjectDownloader.java
- talend-component-kit-intellij-plugin/src/main/java/org/talend/sdk/component/intellij/module/TalendModuleBuilder.java
- talend-component-kit-intellij-plugin/src/main/java/org/talend/sdk/component/intellij/module/step/StarterStep.java
- talend-component-kit-intellij-plugin/src/main/resources/META-INF/plugin.xml
> TCOMP-805 : intellij plugin - better handling of load spinner

- documentation/src/main/antora/modules/ROOT/pages/gallery.adoc
- documentation/src/main/antora/supplemental-ui/css/talend.css
https://jira.talendforge.org/browse/TCOMP-812
Better documentation of dropdown properties in gallery of the documentation
> TCOMP-812 : Gallery dropdown example 

- documentation/src/main/antora/modules/ROOT/nav.adoc
- documentation/src/main/antora/modules/ROOT/pages/component-definition.adoc
- documentation/src/main/antora/modules/ROOT/pages/testing-http.adoc
- documentation/src/main/antora/modules/ROOT/pages/testing-junit.adoc
https://jira.talendforge.org/browse/TCOMP-823
> fix(TCOMP-823) : Fix some documentation errors

- component-form/component-server-proxy-parent/component-server-proxy-play/conf/application.conf
- component-form/component-server-proxy-parent/component-server-proxy-play/pom.xml
- component-form/component-server-proxy-parent/component-server-proxy-play/src/main/java/org/talend/sdk/component/play/owb/PlayContextsService.java
- component-form/component-server-proxy-parent/component-server-proxy-play/src/main/resources/conf/component-proxy.filter.play.conf
- component-form/component-server-proxy-parent/component-server-proxy-play/src/main/resources/conf/component-proxy.loader.play.conf
- component-form/component-server-proxy-parent/component-server-proxy-play/src/main/resources/conf/component-proxy.play.conf
- component-form/component-server-proxy-parent/component-server-proxy-play/src/main/resources/conf/component-proxy.playx.play.conf
- component-form/component-server-proxy-parent/component-server-proxy-play/src/main/resources/openwebbeans/openwebbeans.properties
- component-form/component-server-proxy-parent/component-server-proxy/pom.xml
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/ComponentProxyApplication.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/UiSpecServiceProducer.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/client/ClientProducer.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/client/ConfigurationProxyClient.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/config/ProxyConfiguration.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/front/ConfigurationResourceProxy.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/model/Config.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/ConfigurationService.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/resources/beans.xml
- component-form/component-server-proxy-parent/component-server-proxy/src/main/resources/log4j2.xml
- component-form/component-server-proxy-parent/pom.xml
> [TCOMP-825] add component server proxy

- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/config/SwaggerDoc.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/front/ActionResourceProxy.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/front/ConfigurationResourceProxy.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/ErrorProcessor.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/config/ConfigurationResourceProxyTest.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/front/ActionResourceProxyTest.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/front/ConfigurationResourcesProxyTest.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/test/component/Connection1.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/test/component/TheService.java
> TCOMP-825 : add action resource

- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/client/ComponentClient.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/client/ConfigurationClient.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/front/ActionResource.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/front/ComponentResource.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/front/ConfigurationTypeResource.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/model/Node.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/model/Nodes.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/model/ProxyErrorDictionary.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/model/UiNode.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/ConfigurationService.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/front/ActionResourceTest.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/front/ComponentResourceTest.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/front/ConfigurationResourceTest.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/test/component/Connection1.java
> TCOMP-825 add components endpoint

- component-tools/src/main/java/org/talend/sdk/component/tools/StudioInstaller.java
- component-tools/src/main/java/org/talend/sdk/component/tools/exec/CarMain.java
- component-tools/src/test/java/org/talend/sdk/component/tools/StudioInstallerTest.java
> TCOMP-822 : fix deploy-in-studio and car copy jar lock on win

- component-form/component-server-proxy-parent/component-server-proxy-dependencies/pom.xml
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/client/ComponentClient.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/client/ConfigurationClient.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/client/EnvironmentClient.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/client/RxInvocationCallback.java
> TCOMP-825 : make cxf jaxrs client async

- component-runtime-testing/component-runtime-http-junit/src/main/java/org/talend/sdk/component/junit/http/internal/impl/DefaultResponseLocatorCapturingHandler.java
- component-runtime-testing/component-runtime-http-junit/src/main/java/org/talend/sdk/component/junit/http/internal/impl/PassthroughHandler.java
> TCOMP-875 - Error stream can be null in http request

- README.adoc
Some configuration required for a complete build (noted on Fedora 28 and Ubuntu), usually due to nodegit requirements.
Doc/HowTo address some specific build errors.
> doc: Address some build config on linux.

- component-tools-webapp/src/main/frontend/package-template.json
the previous PR has broken the package template
> chore: backport change into package-template

- documentation/src/main/antora/modules/ROOT/pages/component-definition.adoc
- documentation/src/main/antora/modules/ROOT/pages/component-registering.adoc
- documentation/src/main/antora/modules/ROOT/pages/design.adoc
- documentation/src/main/antora/modules/ROOT/pages/documentation-rest.adoc
- documentation/src/main/antora/modules/ROOT/pages/gallery.adoc
- documentation/src/main/antora/modules/ROOT/pages/release-process.adoc
- documentation/src/main/antora/modules/ROOT/pages/server-uispec.adoc
- documentation/src/main/antora/modules/ROOT/pages/services-actions.adoc
- documentation/src/main/antora/modules/ROOT/pages/services-built-in.adoc
- documentation/src/main/antora/modules/ROOT/pages/services-custom-api.adoc
- documentation/src/main/antora/modules/ROOT/pages/services-interceptors.adoc
- documentation/src/main/antora/modules/ROOT/pages/services-internationalization.adoc
- documentation/src/main/antora/modules/ROOT/pages/services-pipeline.adoc
- documentation/src/main/antora/modules/ROOT/pages/studio.adoc
- documentation/src/main/antora/modules/ROOT/pages/testing-beam.adoc
- documentation/src/main/antora/modules/ROOT/pages/testing-best-practices.adoc
- documentation/src/main/antora/modules/ROOT/pages/testing-generating-data.adoc
- documentation/src/main/antora/modules/ROOT/pages/testing-http.adoc
- documentation/src/main/antora/modules/ROOT/pages/testing-junit.adoc
- documentation/src/main/antora/modules/ROOT/pages/testing-maven-passwords.adoc
- documentation/src/main/antora/modules/ROOT/pages/testing-multiple-envs.adoc
- documentation/src/main/antora/modules/ROOT/pages/testing-spark.adoc
> Doc services & testing

- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/AutoChunkProcessor.java
- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/BaseIOHandler.java
- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/InputsHandler.java
- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/OutputsHandler.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/output/ProcessorImpl.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/visitor/ModelVisitor.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/AutoChunkProcessor.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/BaseComponentsHandler.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/junit/SimpleComponentRuleTest.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/junit/component/BatchTransform.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/junit/component/DuplicateEmitTransform.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/junit5/ComponentExtensionTest.java
- component-tools/src/test/java/org/talend/sdk/component/tools/ComponentValidatorTest.java
- component-tools/src/test/java/org/talend/test/failure/aftergroup/MyComponent.java
- component-tools/src/test/java/org/talend/test/failure/aftergroup/MyComponent2.java
- component-tools/src/test/java/org/talend/test/failure/aftergroup/MyComponent3.java
- component-tools/src/test/java/org/talend/test/failure/aftergroup/package-info.java
- component-tools/src/test/resources/org/talend/test/failure/aftergroup/Messages.properties
> TUP-20309 : handle bulk processing in DI

- component-runtime-design-extension/src/main/java/org/talend/sdk/component/design/extension/flows/ProcessorFlowsFactory.java
- component-runtime-design-extension/src/test/java/org/talend/sdk/component/design/extension/flows/ProcessorFlowsFactoryTest.java
https://jira.talendforge.org/browse/TCOMP-890
> Tcomp 890 merge outputs

- documentation/src/main/antora/modules/ROOT/pages/tutorial-talend-intellij-plugin-usage.adoc
- documentation/src/main/antora/modules/ROOT/pages/tutorial-test-rest-api.adoc
- documentation/src/main/antora/modules/ROOT/pages/tutorial-test-your-components.adoc
- documentation/src/main/antora/modules/ROOT/pages/wrapping-a-beam-io.adoc
> Doc review

- component-tools-webapp/src/main/frontend/src/components/Detail/Detail.component.js
- component-tools-webapp/src/main/frontend/src/components/Detail/Detail.connect.js
the submit is broken
the submit now display the results
> chore: fix webapp submit

- Dockerfile
No logs when using command 'docker logs docker_component-server' from 'data-streams' stack.
Added the remove of file '$MEECROWAVE_BASE/conf/log4j2.xml' like in '/component-runtime/.docker/Dockerfile'
> fix(docker logs): Fix default logging on standard output and standard error

- .travis/docker.sh
Not able to set a fixed version not depending of pom.xml version.
Use a the provided DOCKER_IMAGE_VERSION else use <version> from pom.xml
> feat(DOCKER_IMAGE_VERSION as env vairable)

- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/BaseIOHandler.java
https://jira.talendforge.org/browse/TUP-20352
> TUP-20352 : emit null to be handled for condional outputs

- documentation/src/main/antora/modules/ROOT/pages/component-registering.adoc
- documentation/src/main/antora/modules/ROOT/pages/documentation-overview.adoc
- documentation/src/main/antora/modules/ROOT/pages/getting-started.adoc
- documentation/src/main/antora/modules/ROOT/pages/services-pipeline.adoc
> TCOMP doc - fixed links and cross-refs

- component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchema.java
- component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/schema/TypeConversionTest.java
TDI link https://github.com/Talend/tdi-studio-se/pull/2503
> TCOMP-903 : improve number detection and clean unused attributes

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/builtinparams/MaxBatchSizeParamBuilder.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/MaxBatchSizeParamTest.java
- component-runtime-manager/src/test/java/org/talend/test/BulkProcessorWithAdvancedGridLayoutConfig.java
- component-runtime-manager/src/test/java/org/talend/test/BulkProcessorWithAutoLayoutConfig.java
- component-runtime-manager/src/test/java/org/talend/test/BulkProcessorWithGridLayoutConfig.java
- component-runtime-manager/src/test/java/org/talend/test/BulkProcessorWithHorizontalLayoutConfig.java
- component-runtime-manager/src/test/java/org/talend/test/BulkProcessorWithNoConfig.java
- component-runtime-manager/src/test/java/org/talend/test/BulkProcessorWithOptionOrderConfig.java
- component-runtime-manager/src/test/java/org/talend/test/BulkProcessorWithVerticalLayoutConfig.java
- component-runtime-manager/src/test/java/org/talend/test/BulkProcessorWithoutAfterGroup.java
> add test for $maxBatchSize param creation

- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/path/AbsolutePathResolver.java
- component-form/component-form-core/src/test/java/org/talend/sdk/component/form/internal/converter/impl/widget/path/AbsolutePathResolverTest.java
there is a bug in AbsolutePathResolver.java
PR fixes type done in AbsolutePathResolver.java implementation
> fix: fix typo in AbsolutePathResolver, add more test cases

- documentation/src/main/antora/supplemental-ui-poc/partials/navigation-tree.hbs
> changed minimum displayed TOC level to 1 (POC)

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_documentationindex.adoc
> updated index json

- documentation/src/main/antora/modules/ROOT/pages/all-in-one.adoc
- documentation/src/main/antora/modules/ROOT/pages/index-pdf-tutorials.adoc
> rearranged PDF version

- documentation/src/main/antora/modules/ROOT/nav.adoc
- documentation/src/main/antora/modules/ROOT/pages/tutorial-handle-talend-component-migration.adoc
https://jira.talendforge.org/browse/TCOMP-916
> doc(TCOMP-916) : add a tutorial about component migration

- documentation/src/main/antora/modules/ROOT/pages/tutorial-create-my-first-component.adoc
> meta desc and keywords for component creation getting started tutorial

- component-runtime-manager/pom.xml
- container/container-core/pom.xml
- pom.xml
> Fix test after ziplock upgrade

- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/BaseIOHandler.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/InputsHandler.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/OutputsHandler.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/beam/components/DIBatchSimulationTest.java
> TCOMP-1063 : integrate the Record api to the studio

- component-tools/src/main/java/org/talend/sdk/component/tools/ComponentValidator.java
- component-tools/src/test/java/org/talend/sdk/component/tools/ComponentValidatorTest.java
- component-tools/src/test/resources/org/talend/test/failure/noupdatematching/Messages.properties
- component-tools/src/test/resources/org/talend/test/failure/updatableafter/Messages.properties
- component-tools/src/test/resources/org/talend/test/failure/updatebadtype/Messages.properties
- component-tools/src/test/resources/org/talend/test/valid/datastore/Messages.properties
- component-tools/src/test/resources/org/talend/test/valid/update/Messages.properties
- talend-component-kit-intellij-plugin/src/main/java/org/talend/sdk/component/intellij/service/SuggestionServiceImpl.java
> TCOMP-1049 : fix actions displayname validator using new actions path

- documentation/src/main/antora/modules/ROOT/pages/how-to-contribute.adoc
> replace backslashes with forward slashes

- component-studio/pom.xml
> add component-form-core to studio dependecies

- container/container-core/src/main/java/org/talend/sdk/component/classloader/ConfigurableClassLoader.java
https://jira.talendforge.org/browse/TCOMP-1075
> TCOMP-1075 : disable JarFile cache in our classloader and close stream

- component-tools/src/main/java/org/talend/sdk/component/tools/ComponentValidator.java
- component-tools/src/test/java/org/talend/sdk/component/tools/ComponentValidatorTest.java
- component-tools/src/test/java/org/talend/test/failure/multipleinputsforoutput/MyComponent.java
- component-tools/src/test/java/org/talend/test/failure/multipleinputsforoutput/package-info.java
- component-tools/src/test/resources/org/talend/test/failure/multipleinputsforoutput/Messages.properties
- documentation/src/main/antora/modules/ROOT/pages/build-tools-gradle.adoc
- documentation/src/main/antora/modules/ROOT/pages/build-tools-maven.adoc
- gradle-talend-component/src/main/java-templates/org/talend/sdk/component/gradle/TaCoKitExtension.java
- gradle-talend-component/src/main/java/org/talend/sdk/component/gradle/ValidateTask.java
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/ValidateComponentMojo.java
https://jira.talendforge.org/browse/TCOMP-1069
> TCOMP-1069 : validation - outputs must have only one Input param

- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchema.java
> fix(TCOMP-1031): fix dataset parameter mapping for DiscoverSchema method

- component-runtime-design-extension/src/test/java/org/talend/sdk/component/design/extension/migration/ConfigurationMigrationTest.java
- component-runtime-design-extension/src/test/java/org/talend/test/MetadataMigrationProcessor.java
> TCOMP-996 : unit test to reproduce the metadata migration issue

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/impl/BeamMapperImpl.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/BeamIOWrappingTest.java
> fix(TCOMP-1120): correct BeamMapperImple.isStream for UnboundedSource

- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/ActionService.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/service/ActionServiceTest.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/test/component/Connection2.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/test/component/TheService.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/test/component/component1/TheService2.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/test/integration/ReferenceServiceImpl.java
https://jira.talendforge.org/browse/TCOMP-1129
> TCOMP-1129 : form core - $selfReference breaks triggers

- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/ActionService.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/service/ActionServiceTest.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/test/component/Connection2.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/test/component/TheService.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/test/integration/ReferenceServiceImpl.java
> fix(TCOMP-1129): fix of resolve $selfReference for ActionService

- pom.xml
I do not have the environment to test it.
R: @rmannibucau can you review and test it?
Beam 2.8 was released
It changes Beam dependency to v2.8.0
> [TCOMP-1145] Upgrade beam dependency to 2.8.0

- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/ModelEnricherService.java
> remove duplicate trigger for reloadFromParentEntityIdAndType

- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/ConfigurationFormatterImpl.java
> ignore null values form array

- documentation/src/main/antora/modules/ROOT/pages/component-loading.adoc
> doc: fix typo in doc of plugin part

- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/ActionService.java
- component-form/component-server-proxy-parent/component-server-proxy/src/main/java/org/talend/sdk/component/proxy/service/ModelEnricherService.java
- component-form/component-server-proxy-parent/component-server-proxy/src/test/java/org/talend/sdk/component/proxy/service/ActionServiceTest.java
> TCOMP-1156: keep datasetmetadat while reloading the form from child

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/chain/AutoChunkProcessor.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/chain/internal/JobImpl.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/chain/JobTest.java
- component-runtime-manager/src/test/java/org/talend/test/FileOutput.java
- component-runtime-testing/component-runtime-junit/pom.xml
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/BaseComponentsHandler.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/AutoChunkProcessor.java
https://jira.talendforge.org/browse/TCOMP-1185
> TCOMP-1185 : support maxBatchSize in job test runner for standalone mode

- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/info/ServerInfo.java
Enable secure processing on SAXParserFactory instances
> Enable secure processing on SAXParserFactory instances

- documentation/src/main/antora/modules/ROOT/pages/record-types.adoc
- documentation/src/main/antora/modules/ROOT/pages/tutorial-create-my-first-component.adoc
…ted record type guess schema sample to reflect the datastore/dataset constraints
> doc - temporary updates for dataset/datastores in basic tutorial

- component-starter-server/src/main/frontend/src/app/ComponentsContext.js
- component-starter-server/src/main/frontend/src/app/DatasetContext.js
- component-starter-server/src/main/frontend/src/app/DatastoreContext.js
- component-starter-server/src/main/frontend/src/app/components/DatastoreForm/DatastoreForm.component.js
- component-starter-server/src/main/frontend/src/app/components/Finish/Finish.js
- component-starter-server/src/main/frontend/src/app/components/SideMenu/SideMenu.component.js
> fix(starter): no more blank screen

- component-starter-server/src/main/frontend/src/app/ComponentsContext.js
- component-starter-server/src/main/frontend/src/app/DatasetContext.js
- component-starter-server/src/main/frontend/src/app/DatastoreContext.js
- component-starter-server/src/main/frontend/src/app/components/DatasetDelete/DatasetDelete.component.js
- component-starter-server/src/main/frontend/src/app/components/DatasetDelete/index.js
- component-starter-server/src/main/frontend/src/app/components/DatasetList/DatasetList.component.js
- component-starter-server/src/main/frontend/src/app/components/DatasetSchema/DatasetSchema.container.js
- component-starter-server/src/main/frontend/src/app/components/DatastoreDelete/DatastoreDelete.component.js
- component-starter-server/src/main/frontend/src/app/components/DatastoreDelete/index.js
- component-starter-server/src/main/frontend/src/app/components/DatastoreList/DatastoreList.component.js
- component-starter-server/src/main/frontend/src/app/components/Finish/Finish.js
- component-starter-server/src/main/frontend/src/app/components/Help/Help.js
- component-starter-server/src/main/frontend/src/app/components/Processor/Connection/Connection.container.js
- component-starter-server/src/main/frontend/src/app/components/Processor/Processor.js
- component-starter-server/src/main/frontend/src/app/components/SideMenu/SideMenu.component.js
- component-starter-server/src/main/frontend/src/app/components/SideMenu/SideMenu.scss
- component-starter-server/src/main/frontend/talend-scripts.json
- component-starter-server/src/main/frontend/webpack.config.js
This fix multiple feedback:
* blank page on reload
* bad characters appear in some screen (Â)
* add missing delete of datastore/dataset
* re-add delete of component in side panel
> feat(component-starter): add delete dataset

- component-starter-server/src/main/frontend/src/app/components/DatastoreDelete/DatastoreDelete.component.js
- talend-component-kit-intellij-plugin/src/main/java/org/talend/sdk/component/intellij/module/ProjectDownloader.java
- talend-component-kit-intellij-plugin/src/main/resources/META-INF/plugin.xml
> tacokit Idea plugin 1.1.6

- component-starter-server/src/main/frontend/src/app/components/DatasetForm/DatasetForm.container.js
- component-starter-server/src/main/frontend/src/app/index.js
Because if you try to change the name of the dataset you have a white screen (broken JS)
It fix
> fix(starter/webapp/TCOMP-1388): datasetname update

- component-starter-server/src/main/frontend/.gitignore
- component-starter-server/src/main/frontend/src/app/components/Finish/Finish.js
- component-starter-server/src/main/frontend/src/app/index.js
- component-starter-server/src/main/frontend/src/app/intellij.css
Actual master fail to export simple processor if no activate IO
and fail to export input/output if activateIO
update filter on processor to keep every processor 
Bonus: add css which mimic intellij plugin
> fix(TCOMP-1391): processor create without IO

- documentation/src/main/antora/modules/ROOT/pages/index-deploying-components.adoc
> broken link

- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/ImageM2Mojo.java
> [TCOMP-1436]  new way to add additional files to connectors docker image

- component-tools-webapp/src/main/frontend/src/store/componentsList/actions.js
the icon rely on definition to know if it s in the bundle.
check in the default bundle
> feat(tools): add remote icon

- component-form/component-form-model/src/main/java/org/talend/sdk/component/form/model/uischema/UiSchema.java
- component-form/component-form-model/src/test/java/org/talend/sdk/component/form/model/UiTest.java
Property tooltip is added to UiSchema; ( https://jira.talendforge.org/browse/TCOMP-1447 )
Add property tooltip to UiSchema class
> feat(TCOMP-1447): Add tooltip on UiSchema

- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/ImageM2Mojo.java
> TCOMP-1475 : fix classpath calculation

- documentation/src/main/antora/modules/ROOT/pages/record-types.adoc
some imprecisions in the doc
doc fixes.
> doc(record): fixes imprecise sentences.

- documentation/src/main/antora/modules/ROOT/pages/tutorial-create-an-output-component.adoc
https://jira.talendforge.org/browse/TCOMP-1414
> tutorial - hazelcast output component

- documentation/src/main/antora/modules/ROOT/pages/creating-plugins.adoc
> Doc : fix DependenciesResolutionConfiguration in creatingPlugins

- documentation/src/main/antora/modules/ROOT/pages/tutorial-create-an-input-component.adoc
> TCOMP-1414 - Doc hazelcast input tuto

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
- pom.xml
> TCOMP-1613 - Upgrade cxf to 3.3.5

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- pom.xml
> TCOMP-1614 Upgrade groovy to 3.0.0-rc3

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
- pom.xml
> TCOMP-1615 - Upgrade OpenWebBeans to 2.0.14

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
- pom.xml
> TCOMP-1618 - Upgrade Junit to 5.6.0

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
- pom.xml
> TCOMP-1620 - Upgrade to Apache Beam 2.18.0

- component-runtime-beam/pom.xml
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecord.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordTest.java
- component-runtime-testing/component-runtime-beam-junit/pom.xml
- component-runtime-testing/component-runtime-junit/pom.xml
- component-studio/pom.xml
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
- images/component-server-image/pom.xml
- pom.xml
- sample-parent/sample-beam/pom.xml
> TCOMP-1619 - Handle correctly DATETIME field type on AvroRecord

- .travis/install.sh
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/environment/Dependencies.java
- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/info/ServerInfo.java
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_sample-index.adoc
- sample-parent/documentation-sample/_src/build/Bundles.groovy
> TCOMP-1623 - Change scheme for maven repos

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
- pom.xml
> TCOMP-1621 - Upgrade to Johnzon 1.2.3

- component-api/src/main/java/org/talend/sdk/component/api/component/Icon.java
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
> TCOMP-1622 - [DOC] @Icon is not supported on datastore/dataset

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
- pom.xml
> TCOMP-1625 : Upgrade to xbean 4.16

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- pom.xml
> TCOMP-1627 : Upgrade to Apache Beam 2.19.0

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordConverters.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordConvertersTest.java
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
> TCOMP-1628 - Manage BigDecimal in RecordConverter

- component-runtime-manager/pom.xml
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/ComponentManagerTest.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/LocalConfigurationServiceTest.java
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
> TCOMP-1629 - Translate environment keys for LocalConfiguration

- documentation/src/main/antora/modules/ROOT/pages/compatibility.adoc
- documentation/src/main/antora/modules/ROOT/pages/component-defining-custom-icon.adoc
- documentation/src/main/antora/modules/ROOT/pages/component-registering.adoc
- documentation/src/main/antora/modules/ROOT/pages/icons.adoc
- documentation/src/main/antora/modules/ROOT/pages/studio-from-car.adoc
> [Doc] DOCT-13264 - details about icons + compatibility information

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
- pom.xml
> TCOMP-1634 - Upgrade tomcat to 9.0.31

- talend-component-kit-intellij-plugin/pom.xml
- talend-component-kit-intellij-plugin/src/build/IntelliJPublish.groovy
> TCOMP-1636 - fix intellij-plugin release deployment

- component-tools/src/main/java/org/talend/sdk/component/tools/ComponentValidator.java
- component-tools/src/test/java/org/talend/sdk/component/tools/ComponentValidatorTest.java
- component-tools/src/test/java/org/talend/sdk/component/tools/ScanTaskTest.java
- component-tools/src/test/java/org/talend/test/failure/wording/component/MyComponent.java
- component-tools/src/test/java/org/talend/test/failure/wording/component/package-info.java
- component-tools/src/test/java/org/talend/test/failure/wording/option/MyComponent.java
- component-tools/src/test/java/org/talend/test/failure/wording/option/package-info.java
- component-tools/src/test/java/org/talend/test/valid/wording/MyComponent.java
- component-tools/src/test/resources/org/talend/test/failure/wording/component/Messages.properties
- component-tools/src/test/resources/org/talend/test/failure/wording/option/Messages.properties
- component-tools/src/test/resources/org/talend/test/valid/wording/Messages.properties
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/ValidateComponentMojo.java
> TCOMP-1645 - Ensure correct wording is used in @Documentation

- component-tools/src/main/java/org/talend/sdk/component/tools/ComponentValidator.java
- component-tools/src/test/java/org/talend/sdk/component/tools/ComponentValidatorTest.java
> fix(TCOMP-1694): make the validateSvg argument effective

- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/NativeWrappedIOTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/chain/BeamJobTest.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/ComponentManagerTest.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/chain/JobTest.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/BaseComponentsHandler.java
- documentation/src/main/antora/site-template.yml
Make component manager real singleton (except it can be changed for unit test)
https://jira.talendforge.org/browse/TCOMP-1721
> fix(TCOMP-1721) : component manager as real singleton

- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/NativeWrappedIOTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/chain/BeamJobTest.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/ComponentManagerTest.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/chain/JobTest.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/BaseComponentsHandler.java
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
> fix(TCOMP-1721): Component manager is not thread safe

- component-tools/src/main/java/org/talend/sdk/component/tools/exec/CarMain.java
https://jira.talendforge.org/browse/TDI-44271
> feat(TDI-44271): Allow force install .car

- component-runtime-beam/pom.xml
- singer-parent/component-kitap/pom.xml
> fix(TCOMP-1739) Use scala version defined on parent for Spark related components

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/util/LazyMap.java
* Do not use LazyMap computeIfAbsent method recursively
> fix(TCOMP-1750): Deadlock at TPD job

- component-tools/src/main/java/org/talend/sdk/component/tools/validator/PlaceHolderValidator.java
- component-tools/src/test/java/org/talend/sdk/component/tools/ComponentValidatorTest.java
https://jira.talendforge.org/browse/TCOMP-1792 to have better message on place holder missing
> TCOMP-1792 - enrich placeholder missing message

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/ComponentManagerTest.java
https://jira.talendforge.org/browse/TCOMP-1787
> TCOMP-1787 : instance not null of Component Manager

- pom.xml
https://jira.talendforge.org/browse/TDI-45447
> fix(TDI-45447): Upgrade bouncycastle for CVE

- component-api/src/main/java/org/talend/sdk/component/api/record/Record.java
- component-api/src/test/java/org/talend/sdk/component/api/record/RecordTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/coder/registry/SchemaRegistryCoderTest.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
- singer-parent/component-kitap/src/test/java/org/talend/sdk/component/singer/kitap/KitapTest.java
https://jira.talendforge.org/browse/TCOMP-1811
> TCOMP-1811 : primitif to Object

- component-api/src/main/java/org/talend/sdk/component/api/component/Metadatas.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/BeamComponentExtensionTest.java
- component-runtime-design-extension/src/test/java/org/talend/sdk/component/design/extension/repository/RepositoryModelBuilderTest.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentFamilyMeta.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/reflect/ComponentMetadataService.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/reflect/ComponentModelService.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/ProcessorMetaTest.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResourceImpl.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/front/ComponentResourceImplTest.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/test/InitTestInfra.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/test/model/ListInput.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/test/model/MetadataEnricher.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/test/model/MetadataEnricherLowestPriority.java
- component-spi/src/main/java/org/talend/sdk/component/spi/component/ComponentMetadataEnricher.java
- documentation/src/main/antora/modules/ROOT/pages/component-registering.adoc
https://jira.talendforge.org/browse/TCOMP-1841
> feat(TCOMP-1841): Add metadata to components

- component-api/src/main/java/org/talend/sdk/component/api/record/Record.java
- component-api/src/test/java/org/talend/sdk/component/api/record/RecordTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/coder/registry/SchemaRegistryCoderTest.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
- singer-parent/component-kitap/src/test/java/org/talend/sdk/component/singer/kitap/KitapTest.java
> Tcomp 1811 revert

- component-api/src/main/java/org/talend/sdk/component/api/service/discovery/DiscoverDataset.java
- component-api/src/main/java/org/talend/sdk/component/api/service/discovery/DiscoverDatasetResult.java
- component-tools/src/test/java/org/talend/sdk/component/tools/validator/ActionValidatorTest.java
https://jira.talendforge.org/browse/TDI-45543
Some fixes
> feat(TDI-45543) : Some fixes for crawling

- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-api/src/main/java/org/talend/sdk/component/api/service/schema/Schema.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/avro/AvroSchemas.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecord.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchema.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaBuilder.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/JsonSchemaSerializationTest.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/SchemaImpl.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/Schemas.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/front/beam/BeamActionSerializationTest.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/MappingUtils.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/record/MappingUtilsTest.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/studio/DynamicColumnsTest.java
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_actions.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
https://jira.talendforge.org/browse/TCOMP-1681
> feat(TCOMP-1681): add props to schema

- component-api/src/main/java/org/talend/sdk/component/api/service/http/Base.java
- component-api/src/main/java/org/talend/sdk/component/api/service/http/HttpClient.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/http/HttpRequestCreator.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/http/RequestParser.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/http/RequestParserTest.java
https://jira.talendforge.org/browse/TCOMP-1851
Give possibility to make Http Service stateless.
Annotation @Base for services.
> TCOMP-1851 : add @Base annotation for http request

- documentation/src/main/antora/modules/ROOT/pages/services-built-in.adoc
https://jira.talendforge.org/browse/TCOMP-1851
modify doc
> TCOMP-1851 : doc for base

- component-api/src/main/java/org/talend/sdk/component/api/component/AfterVariables.java
- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-api/src/test/java/org/talend/sdk/component/api/record/SchemaTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordBuilderTest.java
https://jira.talendforge.org/browse/TCOMP-1886
> TCOMP-1886 : schema sanitize

- component-api/src/main/java/org/talend/sdk/component/api/record/Record.java
- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-api/src/main/java/org/talend/sdk/component/api/service/record/RecordBuilderFactory.java
- component-api/src/test/java/org/talend/sdk/component/api/record/SchemaTest.java
- component-api/src/test/java/org/talend/sdk/component/api/service/interceptor/InterceptorHandlerTest.java
- component-api/src/test/java/org/talend/sdk/component/api/service/record/RecordBuilderFactoryTest.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
https://jira.talendforge.org/browse/TCOMP-1884
Add util method on Record.Builder
Unit tests added on component-api & component-runtime-impl
Correction done on sanitzeConnectionName on component-api (after fails on unit test)
> TCOMP-1884 : Add getValue & with method on Record.Builder

- component-server-parent/component-server-api/src/main/java/org/talend/sdk/component/server/api/ConfigurationTypeResource.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/front/ConfigurationTypeResourceImpl.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/front/ConfigurationTypeResourceImplTest.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/test/jdbc/JdbcDataSet.java
https://jira.talendforge.org/browse/TCOMP-1815
> feat(TCOMP-1815): return a proper error payload for migration

- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-api/src/test/java/org/talend/sdk/component/api/record/SchemaTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordBuilderTest.java
https://jira.talendforge.org/browse/TCOMP-1886
back to buggy function
> TCOMP-1886 revert to bugged function

- component-runtime-beam/pom.xml
- component-runtime-beam/src/it/serialization-over-cluster/pom.xml
- component-runtime-beam/src/main/build/RunnerDependencies.groovy
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/customizer/Indices.java
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/junit/environment/builtin/beam/SparkRunnerEnvironment.java
- pom.xml
> TCOMP-1893 Upgrade to Beam 2.29.0 and use Beam's Spark 3 specific module

- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-api/src/test/java/org/talend/sdk/component/api/record/SchemaTest.java
https://jira.talendforge.org/browse/TCOMP-1886
make new sanitize compatible with old one.
> TCOMP-1886 : sanitize compatible with old one

- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
https://jira.talendforge.org/browse/TCOMP-1919
> TCOMP-1919 : add encoding

- pom.xml
- reporting/pom.xml
https://jira.talendforge.org/browse/TDI-45570
> feat(TDI-45570): add code coverage reporting module

- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-api/src/test/java/org/talend/sdk/component/api/record/SchemaTest.java
https://jira.talendforge.org/browse/TCOMP-1936
> TCOMP-1936 : properties as json

- component-api/src/main/java/org/talend/sdk/component/api/service/BaseService.java
- component-api/src/main/java/org/talend/sdk/component/api/service/http/Configurer.java
- component-api/src/main/java/org/talend/sdk/component/api/service/record/RecordService.java
- component-api/src/main/java/org/talend/sdk/component/api/service/serialization/Serial.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/serialization/SerializableService.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/ServiceHelper.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/ServiceHelperTest.java
- container/container-core/src/main/java/org/talend/sdk/component/classloader/ThreadHelper.java
https://jira.talendforge.org/browse/TCOMP-1885
> TCOMP-1885 : make services explicitly serializable

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/SchemaImpl.java
https://jira.talendforge.org/browse/TCOMP-1876
> TCOMP-1876 : schema impl immutable

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecord.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordBuilderTest.java
https://jira.talendforge.org/browse/TCOMP-1904
> TCOMP-1904 : avro sub rec

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordImpl.java
https://jira.talendforge.org/browse/TCOMP-1906
> TCOMP-1906 : record impl with equals and hash

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecord.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordBuilderTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordTest.java
https://jira.talendforge.org/browse/TCOMP-1987
> TCOMP-1987 : Avro record array

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaBuilder.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordBuilderTest.java
https://jira.talendforge.org/browse/TCOMP-1957
Fix potential bug on Avro implementation of TCK Record.
> TCOMP-1957 : To Avro element schema

- component-api/src/main/java/org/talend/sdk/component/api/service/BaseService.java
https://jira.talendforge.org/browse/TCOMP-1996
> TCOMP-1996 : change BaseService class

- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-api/src/main/java/org/talend/sdk/component/api/service/schema/Schema.java
- component-api/src/test/java/org/talend/sdk/component/api/record/SchemaTest.java
- component-api/src/test/java/org/talend/sdk/component/api/service/record/RecordBuilderFactoryTest.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/AvroRecordBuilderFactoryProvider.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchema.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/coder/registry/SchemaRegistryCoderTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordBuilderTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaCacheTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaConverterTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/JsonSchemaSerializationTest.java
- component-runtime-impl/pom.xml
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordBuilderFactoryImpl.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordImpl.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/SchemaImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/SchemaImplTest.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/RecordPointerImplTest.java
- component-starter-server/src/test/java/org/talend/sdk/component/starter/server/front/apidemo/component/service/MockTableService.java
- documentation/src/main/java/org/talend/runtime/documentation/Generator.java
- documentation/src/main/java/org/talend/runtime/documentation/component/service/MockTableService.java
https://jira.talendforge.org/browse/TCOMP-2049
> fix(TCOMP-2049): revert Entry move interface to class

- bom/pom.xml
> TCOMP-1950 deploy info

- Jenkinsfile
https://jira.talendforge.org/browse/TCOMP-1950 - update jenkins
> fix(TCOMP-1950) : update jenkins.

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2030
back port to 1.38 for 1.38.5 version
> fix(TCOMP-2030) : tomcat version

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchema.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaTest.java
https://jira.talendforge.org/browse/TCOMP-2057
> TCOMP-2057 : optim avro schema

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecord.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchema.java
https://jira.talendforge.org/browse/TCOMP-2063
> fix(TCOMP-2063) : Avro record constructor

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/SchemaImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/SchemaImplTest.java
https://jira.talendforge.org/browse/TCOMP-2067
> TCOMP-2067 : fix move after

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/ProducerFinderImpl.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/api/ComponentInstantiator.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/ProducerFinderImplTest.java
https://jira.talendforge.org/browse/TCOMP-2064
> fix(TCOMP-2064) : join processor NPE

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/proxy/JavaProxyEnricherFactory.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/proxy/JavaProxyEnricherFactoryTest.java
- component-runtime-manager/src/test/resources/org/talend/sdk/component/runtime/manager/proxy/Messages.properties
https://jira.talendforge.org/browse/TCOMP-2065
> fix(TCOMP-2065) : internationalizable services

- component-api/src/main/java/org/talend/sdk/component/api/service/record/RecordBuilderFactory.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderFactoryImplTest.java
https://jira.talendforge.org/browse/TCOMP-1763
> TCOMP-1763 declare factory serializable

- component-api/src/main/java/org/talend/sdk/component/api/record/Record.java
- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-api/src/test/java/org/talend/sdk/component/api/record/RecordTest.java
- component-api/src/test/java/org/talend/sdk/component/api/record/SchemaTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderFactoryImplTest.java
https://jira.talendforge.org/browse/TCOMP-2071
> fix(TCOMP-2071): Define default methods on API interfaces

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/ComponentManagerTest.java
- component-runtime-manager/src/test/resources/settings/settings-commented.xml
- component-runtime-manager/src/test/resources/settings/settings-ko.xml
- component-runtime-manager/src/test/resources/settings/settings-ok-spaced-mixed-case.xml
- component-runtime-manager/src/test/resources/settings/settings-ok-spaced.xml
- component-runtime-manager/src/test/resources/settings/settings-ok.xml
https://jira.talendforge.org/browse/TCOMP-2082
> fix(TCOMP-2082): ComponentManager's findDefaultM2 method takes comment as granted

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/internationalization/ComponentBundle.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResourceImpl.java
https://jira.talendforge.org/browse/TCOMP-2084
> feat(TCOMP-2084): add i18n-ed metadata

- container/container-core/src/main/java/org/talend/sdk/component/dependencies/maven/MvnCoordinateToFileConverter.java
- container/container-core/src/test/java/org/talend/sdk/component/dependencies/maven/MvnCoordinateToFileConverterTest.java
* add case with classifier
https://jira.talendforge.org/browse/TCOMP-2092
> chore(TCOMP-2092): improve mvn coordinate resolver

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/AvroRecordBuilderFactoryProvider.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroEntryBuilder.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecord.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaBuilder.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/coder/registry/SchemaRegistryCoderTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordBuilderTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaTest.java
https://jira.talendforge.org/browse/TCOMP-2119
Allow array to have null elements.
> TCOMP-2119 : Avro record to contains arrays with null

- component-runtime-manager/pom.xml
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/MavenRepositoryDefaultResolver.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/MavenRepositoryResolver.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/path/PathHandler.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/path/PathHandlerImpl.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/MavenRepositoryResolverTest.java
- component-runtime-manager/src/test/resources/settings/settings-prop-env.xml
- component-runtime-manager/src/test/resources/settings/settings-prop-user.xml
- component-runtime-manager/src/test/resources/settings/settings-tilde.xml
- component-runtime-manager/src/test/resources/settings/settings-win.xml
https://jira.talendforge.org/browse/TCOMP-2098
> feat(TCOMP-2098): improve m2 discovery

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecord.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordTest.java
https://jira.talendforge.org/browse/TCOMP-2127
> TCOMP-2127 : fix array

- pom.xml
- talend-component-maven-plugin/pom.xml
- talend-component-maven-plugin/src/it/dependency/pom.xml
- talend-component-maven-plugin/src/it/dependency/postbuild.groovy
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/ComponentDependenciesBase.java
https://jira.talendforge.org/browse/TCOMP-2133
> fix(TCOMP-2133): use baseVersion for snapshot artifacts

- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-api/src/test/java/org/talend/sdk/component/api/record/EntriesOrderTest.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaBuilder.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
https://jira.talendforge.org/browse/TCOMP-2123
> TCOMP-2123 : fix move after last

- component-server-parent/component-server-model/src/main/java/org/talend/sdk/component/server/front/model/ComponentIndex.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResourceImpl.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/front/ComponentResourceImplTest.java
https://jira.talendforge.org/browse/TCOMP-2171
> feat(TCOMP-2171): add componnent type to index

- Jenkinsfile
https://jira.talendforge.org/browse/TDI-47867
Updated Jenkinsfile to:
1. Only send slack messages to #component-ci for Master and Maintenance builds.
2. Ping with "here" when a build is failing and the previous one was OK.
> chore(TDI-47867) Increase CI build visibility

- component-api/src/main/java/org/talend/sdk/component/api/record/Record.java
- component-api/src/test/java/org/talend/sdk/component/api/record/RecordTest.java
https://jira.talendforge.org/browse/TCOMP-2176
> TCOMP-2176: fix infinite loop

- Jenkinsfile
* Only JenkinsFile edition
Improve visibilities on @Disabled code and on TODO and FIXME
https://jira.talendforge.org/browse/TDI-47901
New graphics on internal Jenkins dashboard
> TDI-47901: Disabled, TODO and FIXME monitoring

- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/configuration/WebSocketBroadcastSetup.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/front/ConfigurationTypeResourceImplTest.java
The idea is to provide the support partial message buffers in the WebSocket.
The approach to gathering input streams is not ideal
> fix(TCOMP-2190): support partial websocket

- component-api/src/main/java/org/talend/sdk/component/api/record/Record.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
> feat(TCOMP-2219): UpdateEntry to convert value from schema type

- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchema.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchemaTest.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/schema/TypeConversionTest.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/schema/package-info.java
https://jira.talendforge.org/browse/TCOMP-2182
https://github.com/Talend/component-runtime/pull/598
master:
https://github.com/Talend/tdi-studio-se/pull/7851
8.0:
https://github.com/Talend/tdi-studio-se/pull/7852
> fix(TCOMP-2182): pass version to guess schema

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/TalendIO.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/TalendIOTest.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/input/PartitionMapperImpl.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/input/Streaming.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/input/StreamingInputImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/input/StreamingInputImplTest.java
https://jira.talendforge.org/browse/TCOMP-2107
> feat(TCOMP-2107): Implement a stop strategy for streaming input connectors

- bom/pom.xml
- pom.xml
> Feat(TCOMP-2223) Upgrade log4j to 2.18.0

- bom/pom.xml
- pom.xml
> feat(TCOMP-2227) Upgrade commons-io to 2.9.0

- bom/pom.xml
> feat(TCOMP-2229)Upgrade jcommander to 1.81

- component-runtime-impl/pom.xml
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/input/Streaming.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/input/StreamingInputImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/input/StreamingInputImplTest.java
- component-runtime-impl/src/test/resources/log4j2.xml
https://jira.talendforge.org/browse/TCOMP-2234
> feat(TCOMP-2234): override blocking read process in streaming connectors

- bom/pom.xml
- pom.xml
https://jira.talendforge.org/browser/TCOMP-2232
> Feat(TCOMP-2232): Upgrade slf4j to 1.7.34

- pom.xml
https://jira.talendforge.org/browser/TCOMP-2238
> Feat TCOMP-2238	Upgrade jib-core to 0.16.0

- pom.xml
https://jira.talendforge.org/browser/TCOMP-2228
> Feat(TCOMP-2228) Upgrade git-commit-id-plugin to 4.9.9

- pom.xml
Reverts Talend/component-runtime#611
> Revert "Feat(TCOMP-2228) Upgrade git-commit-id-plugin to 4.9.9"

- component-server-parent/component-server/pom.xml
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2228
> feat(TCOMP-2228): bump git-commit-id-plugin to 4.9.10

- Jenkinsfile
- ci/Jenkinsfile-scan
- images/pom.xml
Upgrade TSBI to 3.0.5 includes now RockyLinux
> feat(TCOMP-2264): bump tsbi to 3.0.5

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2257
> Feat[TCOMP-2257]:Upgrade meecrowave to 1.2.14

- bom/pom.xml
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2251
> feat(TCOMP-2251): Upgrade jackson to 2.13.3

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2263
> Feat[TCOMP-2263]:Upgrade openwebbeans-se to 2.0.27

- Jenkinsfile
Reverts Talend/component-runtime#633
> Revert "Chore(TDI-48532) Automated malformed encoding fix"

- Jenkinsfile
* https://jira.talendforge.org/browse/TDI-47931 ([internal] TestContainer: Can not connect to Ryuk)
* Update CI to use Docker In Docker (DinD) instead of Docker Sock.
> chore(TDI-47931): Fix TestContainer-Ryuk timeout with Docker in Docker

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/BeamProducerFinder.java
> chore(TCOMP-2241): backport classloader fix to run ProducerFinder pipeline

- container/container-core/src/main/java/org/talend/sdk/component/container/ContainerManager.java
- container/container-core/src/test/java/org/talend/sdk/component/ContainerManagerTest.java
- container/container-core/src/test/java/org/talend/sdk/component/dependencies/maven/ArtifactTest.java
- container/container-core/src/test/java/org/talend/sdk/component/dependencies/maven/MvnCoordinateToFileConverterTest.java
- container/container-core/src/test/java/org/talend/sdk/component/dependencies/maven/MvnDependenciesTxtArtifactConverterTest.java
- container/container-core/src/test/java/org/talend/sdk/component/dependencies/maven/MvnDependencyListLocalRepositoryResolverTest.java
https://jira.talendforge.org/browse/TCOMP-2285
> feat(TCOMP-2285): allow jira ticket in artifact version

- component-api/src/main/java/org/talend/sdk/component/api/configuration/Option.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/base/LifecycleImpl.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/input/Streaming.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/input/StreamingInputImpl.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/visitor/ModelVisitor.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/base/LifecycleImplTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/input/StreamingInputImplTest.java
- component-tools/pom.xml
- component-tools/src/main/java/org/talend/sdk/component/tools/validator/OptionParameterValidator.java
- component-tools/src/main/java/org/talend/sdk/component/tools/validator/Validators.java
- component-tools/src/test/java/org/talend/sdk/component/tools/validator/OptionParameterValidatorTest.java
- documentation/src/main/antora/modules/ROOT/pages/component-implementing-streaming.adoc
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2291
https://jira.talendforge.org/browse/TCOMP-2291
> feat(TCOMP-2291): pass timeout & max records option

- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
I should definitely set up the formatter correctly in my IDE 😅
> chore(TDP-11601): fix formatting issues in tests after entry name order

- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchema.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchemaTest.java
- documentation/src/main/antora/modules/ROOT/pages/studio-schema.adoc
https://jira.talendforge.org/browse/TCOMP-2235
**Related PR**
- 
- https://github.com/Talend/component-runtime/pull/664
- https://github.com/Talend/tdi-studio-se/pull/8223
- https://github.com/Talend/tdi-studio-se/pull/8269
> feat(TCOMP-2235): add discover schema ext to input

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2328
https://jira.talendforge.org/browse/TCOMP-2328
> fix(TCOMP-2328): CVE-2022-40152,com.fasterxml.woodstox:woodstox-core

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2328
https://jira.talendforge.org/browse/TCOMP-2328
> fix(TCOMP-2328): CVE-2022-40152,com.fasterxml.woodstox:woodstox-core:(6.2.6,6.2.7,6.2.8,6.2.1,5.3.0 <6.4.0)

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2327
> fix(TCOMP-2327):CVE-2022-46364,org.apache.cxf:cxf-core:3.5.2

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2327
> fix(TCOMP-2327):CVE-2022-46364,org.apache.cxf:cxf-core:3.4.4

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2327
> fix(TCOMP-2327):CVE-2022-46364,org.apache.cxf:cxf-core:3.4.4,3.5.2

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
https://jira.talendforge.org/browse/TCOMP-2328
https://jira.talendforge.org/browse/TCOMP-2328
> fix(TCOMP-2328): update document before release

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/reflect/Defaults.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/reflect/JavaVersion.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/reflect/JavaVersionTest.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/asm/Unsafes.java
https://jira.talendforge.org/browse/TCOMP-2330
https://jira.talendforge.org/browse/TCOMP-2330
> fix(TCOMP-2330): A better way to check the JVM version

- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/configuration/ComponentServerConfiguration.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/service/ComponentManagerService.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/service/jcache/FrontCacheResolver.java
https://jira.talendforge.org/browse/TCOMP-2336
> feat(TCOMP-2336): Allow component-server to not fail on empty/not found component-registry descriptor

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordConverters.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRecordVisitor.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRowStructVisitor.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DynamicMetadataWrapper.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DynamicWrapper.java
https://jira.talendforge.org/browse/TCOMP-2165
https://jira.talendforge.org/browse/TCOMP-2165
> fix(TCOMP-2165): [TCK]: tck connector need studio TIS license, as it hard depend on routines.system.Dynamic class

- bom/pom.xml
- container/container-core/src/test/java/org/talend/sdk/component/classloader/ConfigurableClassLoaderTest.java
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2347
> feat(TCOMP-2347): update indirect test dependencies

- component-tools/src/test/java/org/talend/sdk/component/tools/validator/OutputConnectionValidatorTest.java
Add a direct unit test on OutputConnectionValidator : https://jira.talendforge.org/browse/TCOMP-2314
No change to runtime code, only unit test added.
> TCOMP-2314: validator unit test

- pom.xml
checkstyle-plugin is in 3.1.2 = checkstyle 8.x
Maven advise using >= 8.30
Bump to checkstyle-plugin is in 3.2.1 = checkstyle 9.3
> chore(TCOMP-2361) checkstyle bump

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2405
> feat(TCOMP-2405): Upgrade snakeyaml to 2.0

- Jenkinsfile
Correct CI small issue on sonar call
> feat(2402) correct sonar issue

- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/MavenRepositoryResolverTest.java
https://jira.talendforge.org/browse/TCOMP-2178
> Fix{TCOMP-2178): Missing UT for MavenRepositoryDefaultResolver use of file separators

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2412
https://jira.talendforge.org/browse/TCOMP-2412
> fix(TCOMP-2412): Upgrade org.apache.tomcat:tomcat-catalina to 9.0.69

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
- images/component-server-image/pom.xml
https://jira.talendforge.org/browse/TCOMP-2414
> feat(TCOMP-2414): add add-opens

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/api/ComponentInstantiator.java
https://jira.talendforge.org/browse/TCOMP-2383
> feat((TCOMP-2383): decrease log level when component not found

- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchema.java
https://jira.talendforge.org/browse/TCOMP-2343
**Related PR**
- https://github.com/Talend/component-runtime/pull/707 (component-runtime)
- https://github.com/Talend/tdi-studio-se/pull/8625 (tdi-studio-se master)
- https://github.com/Talend/tdi-studio-se/pull/8626 (tdi-studio-se maintenance/8.0)
> feat(TCOMP-2343): improve guess schema error message

- component-api/src/main/java/org/talend/sdk/component/api/record/Record.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/MappingUtils.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/configuration/PropertiesSetup.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRowStructVisitor.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/record/VisitorsTest.java
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
- images/component-server-image/pom.xml
- singer-parent/component-kitap/pom.xml
- singer-parent/component-kitap/src/main/java/org/talend/sdk/component/singer/kitap/RecordJsonMapper.java
- singer-parent/component-kitap/src/test/java/org/talend/sdk/component/singer/kitap/RecordJsonMapperTest.java
- update documentation
- fix formatting from merged PR
> feat(TCOMP-2414): fix extra package typo

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
> chore(changelog): update changelog for release

- .jenkins/scripts/docker_build.sh
An error blocked the master branch script execution, default values were not setup correctly
> bug(TCOMP-2407) Correct docker build script on default values

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/MappingUtils.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/MappingUtilsTest.java
https://jira.talendforge.org/browse/TCOMP-2426
> fix(TCOMP-2426): add instant to long conversion

- bom/pom.xml
- component-runtime-testing/component-runtime-http-junit/pom.xml
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2423 - Upgrade netty to 4.1.92.Final
https://jira.talendforge.org/browse/TCOMP-2424 - Upgrade jackson to 2.15.0
> security upgrades

- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/configuration/PropertiesSetup.java
- images/component-server-image/pom.xml
- images/component-server-image/src/main/jib/entrypoint.sh
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2435
> fix(TCOMP-2435): fix entrypoint.sh

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecord.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaBuilder.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordTest.java
https://jira.talendforge.org/browse/TCOMP-2447
> feat(TCOMP-2447): Revert datetime instant management changes on AvroSchema

- component-tools/src/main/java/org/talend/sdk/component/tools/CarBundler.java
- component-tools/src/main/java/org/talend/sdk/component/tools/exec/CarMain.java
- documentation/src/main/antora/modules/ROOT/pages/build-tools-maven.adoc
- documentation/src/main/antora/modules/ROOT/pages/studio.adoc
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/CarMojo.java
https://jira.talendforge.org/browse/TCOMP-2443
**Related PR**
- component-runtime : 
- https://github.com/Talend/component-runtime/pull/728
- tdi-studio-se:
-  https://github.com/Talend/tdi-studio-se/pull/8824 (master)
> feat(TCOMP-2443): allow component-server extensions for Studio

- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResourceImpl.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/front/ConfigurationTypeResourceImpl.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/front/ComponentResourceImplTest.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/front/ConfigurationTypeResourceImplTest.java
https://jira.talendforge.org/browse/TCOMP-2428
> feat(TCOMP-2428): Stop deciphering vault secrets in migrations

- component-server-parent/component-server-api/src/main/java/org/talend/sdk/component/server/api/ComponentResource.java
- component-server-parent/component-server-api/src/main/java/org/talend/sdk/component/server/api/ConfigurationTypeResource.java
chore(TCOMP-2197) Correct documentation about identifier list in API call
https://jira.talendforge.org/browse/TCOMP-2197
Only documentation edition.
> chore(TCOMP-2197) Correct documentation about identifier list in API call

- talend-component-maven-plugin/src/it/web/test/tck-component-migrate-api-test/tck_component_migrate_api_test.json
- talend-component-maven-plugin/src/it/web/test/tck-configurationType-migrate-api-test/tck_configurationType_migrate_api_test.json
https://jira.talendforge.org/browse/TCOMP-2475
Align test with requirements
Edit APITester json files
> chore(TCOMP-2475) fix test case after discussion on requirements

- bom/pom.xml
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2507
> feat(TCOMP-2507): Upgrade commons-compress to 1.23.0

- bom/pom.xml
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2508
> feat(TCOMP2508): Upgrade commons-io to 2.13.0

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2509
> feat(TCOMP-2509): Upgrade cxf to 3.5.6

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2510
> feat(TCOMP-2510): Upgrade gmavenplus to 1.13.1

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2511
> feat(TCOMP-2511): Upgrade groovy to 3.0.18

- bom/pom.xml
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2512
> feat(TCOMP-2512): Upgrade jackson-databind/jackson to 2.15.2

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2513
https://jira.talendforge.org/browse/TCOMP-2513
> feat(TCOMP-2513): Upgrade jacoco to 0.8.10

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2514
https://jira.talendforge.org/browse/TCOMP-2514
> feat(TCOMP-2514): Upgrade java11.jaxb to 2.3.8

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2515
> feat(TCOMP-2515): Upgrade junit5 to 5.9.3

- ci/Jenkinsfile-scan
https://jira.talendforge.org/browse/TDI-50161
Use docker:23.0.6-dind
> feat(TDI-51161) remove docker sock

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2516
> feat(TCOMP-2516): Upgrade mvn to 3.8.8

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2517
> feat(TCOMP-2517): Upgrade surefire-plugin to 3.0.0

- pom.xml
> feat(TCOMP-2518): Upgrade tomcat to 9.0.78

- Jenkinsfile
https://jira.talendforge.org/browse/TDI-50175
Use docker:23.0.6-dind
> feat(TDI-50175): remove docker sock for jenkins build

- sample-parent/sample-connector/src/main/java/org/talend/sdk/component/test/connectors/service/DiscoverDatasetServices.java
- sample-parent/sample-connector/src/main/resources/org/talend/sdk/component/test/connectors/Messages.properties
- sample-parent/sample-connector/src/main/resources/org/talend/sdk/component/test/connectors/Messages_en.properties
- sample-parent/sample-connector/src/main/resources/org/talend/sdk/component/test/connectors/Messages_fr.properties
- sample-parent/sample-connector/src/main/resources/org/talend/sdk/component/test/connectors/Messages_ja.properties
- sample-parent/sample-connector/src/main/resources/org/talend/sdk/component/test/connectors/Messages_uk.properties
- sample-parent/sample-connector/src/main/resources/org/talend/sdk/component/test/connectors/Messages_zh_CN.properties
- talend-component-maven-plugin/src/it/web/test/pom.xml
- talend-component-maven-plugin/src/it/web/test/tck-action-discoverdataset-api-test/pom.xml
- talend-component-maven-plugin/src/it/web/test/tck-action-discoverdataset-api-test/tck_action_discoverdataset_api_test.json
https://jira.talendforge.org/browse/TCOMP-2458
Cover discoverdataset action
> feat(TCOMP-2458) api test coverage for Cover discoverdataset action

- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_contributors.adoc
> feat： changelog for Release 1.60.0

- component-api/src/main/java/org/talend/sdk/component/api/configuration/ui/widget/Path.java
https://jira.talendforge.org/browse/TDI-47988
https://jira.talendforge.org/browse/TDI-47988
> fix(TDI-47988): [JDBC TCK]: support file field type for file selector ui for tjdbcoutputbulk/tjdbcbulkexec

- sample-parent/sample-connector/src/main/java/org/talend/sdk/component/test/connectors/service/BuiltInSuggestableServices.java
- sample-parent/sample-connector/src/main/resources/org/talend/sdk/component/test/connectors/Messages.properties
- sample-parent/sample-connector/src/main/resources/org/talend/sdk/component/test/connectors/Messages_en.properties
- sample-parent/sample-connector/src/main/resources/org/talend/sdk/component/test/connectors/Messages_fr.properties
- sample-parent/sample-connector/src/main/resources/org/talend/sdk/component/test/connectors/Messages_ja.properties
- sample-parent/sample-connector/src/main/resources/org/talend/sdk/component/test/connectors/Messages_uk.properties
- sample-parent/sample-connector/src/main/resources/org/talend/sdk/component/test/connectors/Messages_zh_CN.properties
- talend-component-maven-plugin/src/it/web/test/pom.xml
- talend-component-maven-plugin/src/it/web/test/tck-action-builtinsuggestable-api-test/pom.xml
- talend-component-maven-plugin/src/it/web/test/tck-action-builtinsuggestable-api-test/tck_action_builtinsuggestable_api_test.json
https://jira.talendforge.org/browse/TCOMP-2461
Cover built_in_suggestable action
> feat(TCOMP-2461) Cover built_in_suggestable action

- component-runtime-testing/component-runtime-http-junit/pom.xml
https://jira.talendforge.org/browse/TCOMP-2525
CVE fix: io.netty:netty-handler:jar:4.1.94.Final - upgrade to 4.1.97.Final
> TCOMP-2525

- bom/pom.xml
- remote-engine-customizer/pom.xml
https://jira.talendforge.org/browse/TCOMP-2526
CVE fix: com.google.guava:guava:jar:31.1-jre:runtime; upgrade to 32.1.2-jre
> fix(TCOMP-2526):

- bom/pom.xml
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2538
org.apache.commons:commons-compress:jar:1.23.0:provided;
> fix(TCOMP-2538): [CVE]:org.apache.commons:commons-compress:jar:1.23.0

- Jenkinsfile
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2539
Upgrade org.eclipse.jgit:jar to 5.13.2.202306221912-r
> fix(TCOMP-2539): Upgrade org.eclipse.jgit:jar to 5.13.2.202306221912-r

- .jenkins/scripts/mvn_sonar_branch.sh
- .jenkins/scripts/mvn_sonar_pr.sh
- Jenkinsfile
- sample-parent/sample-connector/src/main/java/org/talend/sdk/component/test/connectors/config/Auth.java
Correct the sonar ci integration
https://jira.talendforge.org/browse/TDI-49155
> chore(TDI-49155): Add Sonar to GitHub

- .jenkins/scripts/mvn_sonar_pr.sh
- Jenkinsfile
https://jira.talendforge.org/browse/TDI-50338
> chore(TDI-50338): [internal] Fix Sonar diffs on PR builds

- images/pom.xml
https://jira.talendforge.org/browse/TCOMP-2543
> feat(TCOMP-2543): bump tsbi to 4.0.1-20230911145727

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2544
> fix(TCOMP-2544): Upgrade snappy to 1.1.10.5

- component-server-parent/component-server-model/src/main/java/org/talend/sdk/component/server/front/model/ErrorDictionary.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/front/ActionResourceImpl.java
- talend-component-maven-plugin/src/it/web/.jenkins/scripts/server-registry-manual_start.sh
- talend-component-maven-plugin/src/it/web/.jenkins/scripts/tcomp-build-fast.sh
- talend-component-maven-plugin/src/it/web/.jenkins/scripts/tcomp-build-sample-connector.sh
- talend-component-maven-plugin/src/it/web/README.md
Correct specific errors messages
Add new exception
https://jira.talendforge.org/browse/TCOMP-2464
> bug(TDI-2464) correct error messages

- component-api/src/main/java/org/talend/sdk/component/api/record/SchemaProperty.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRecordVisitor.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/record/DiRecordVisitorTest.java
https://jira.talendforge.org/browse/TCOMP-2541
https://jira.talendforge.org/browse/TCOMP-2541
> fix(COMP-2541): Improve performance on dynamic column

- component-runtime-testing/component-runtime-junit/pom.xml
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2550
> feat(TCOMP-2550): Upgrade avro to 1.11.3

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/MappingUtils.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRecordVisitor.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRowStructVisitor.java
https://jira.talendforge.org/browse/TCOMP-2533
https://jira.talendforge.org/browse/TCOMP-2533
> fix(TCOMP-2533): move the verbose debug log to trace for DIRowStructVisitor and DIRecordVisitor and MappingUtils

- component-runtime-beam/pom.xml
https://jira.talendforge.org/browse/TCOMP-2562
> feat(TCOMP-2562): remove grpc from beam-runners-spark-3

- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/front/ApiDemoEndpoints.java
- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/service/info/ServerInfo.java
- images/component-starter-server-image/pom.xml
https://jira.talendforge.org/browse/TCOMP-2564
> fix(TCOMP-2564): component-starter image startup hangs

- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/configuration/WebSocketBroadcastSetup.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/front/ConfigurationTypeResourceImplTest.java
https://jira.talendforge.org/browse/TCOMP-2557
https://jira.talendforge.org/browse/TCOMP-2557
> fix(TCOMP-2557): unable to test connection well if the password contains ^

- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResourceImpl.java
- talend-component-maven-plugin/src/it/web/test/tck-component-dependencies-api-test/tck_component_dependencies_api_test.json
https://jira.talendforge.org/browse/TCOMP-2476
The component issue for getDependencies was not handled.
This PR add it management with a specific 404 error.
Corrected API test according to evolution.
> bug(TCOMP-2476): Manage component not found for getDependencies request

- images/component-server-image/src/main/jib/opt/talend/prometheus-agent/jmx_exporter_config.yaml
- images/component-server-image/src/main/resources/meecrowave.properties
- vault-client/src/main/java/org/talend/sdk/components/vault/jcache/CacheConfigurationFactory.java
https://jira.talendforge.org/browse/TCOMP-2571
> feat(TCOMP-2571): add prometheus jmx management

- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/configuration/StarterConfiguration.java
- images/component-starter-server-image/pom.xml
https://jira.talendforge.org/browse/TCOMP-2585
> feat(TCOMP-2585): fix open and kit version

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/base/lang/exception/InvocationExceptionWrapper.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchema.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchemaTest.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/schema/package-info.java
Reverts Talend/component-runtime#763
> Revert "feat(TCOMP-2342): execute processor mock job"

- Jenkinsfile
- pom.xml
- talend-component-maven-plugin/pom.xml
- talend-component-maven-plugin/src/it/settings.xml
https://jira.talendforge.org/browse/TCOMP-2596
> fix(TCOMP-2596): fix maven plugin ITs

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2590
> feat(TCOMP-2590): upgrade tomcat to 9.0.84

- talend-component-maven-plugin/pom.xml
- talend-component-maven-plugin/src/it/web/.jenkins/scripts/server-registry-init.sh
- talend-component-maven-plugin/src/it/web/.jenkins/settings.xml
Fix TCK API tests following open source changes on talend repositories.
CI update to manage credentials for TCK API tests.
> chore(TCOMP-2597): [Internal] Fix TCK API Tests credentials management following open source repository changes

- bom/pom.xml
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2522
> TCOMP-2522 Upgrade johnzon-mapper to 1.2.21

- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchema.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchemaTest.java
https://jira.talendforge.org/browse/TCOMP-2283
**Related PR**
*component-runtime*
- https://github.com/Talend/component-runtime/pull/838
*Studio*
- https://github.com/Talend/tdi-studio-se/pull/9450 maintenance/8.0
- https://github.com/Talend/tdi-studio-se/pull/9451 master
> feat(TCOMP-2283): Handle Dynamic column in guess schema

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/RecordServiceImpl.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRecordVisitor.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/record/DiRecordVisitorTest.java
https://jira.talendforge.org/browse/TCOMP-2384
> fix(TCOMP-2384): wrong studio mapping in sub records

- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/DependencyConflictsReporterMojo.java
https://jira.talendforge.org/browse/TCOMP-2076
> feat(TCOMP-2076): allow skip DependencyConflictsReporterMojo

- talend-component-maven-plugin/src/it/web/test/pom.xml
https://jira.talendforge.org/browse/TCOMP-2617
Test commit strategy.
> chore(TCOMP-2617): CI: Component Runtime master job is not triggering builds on commits

- talend-component-maven-plugin/src/it/web/test/pom.xml
This reverts commit 8a187ad2295af2b1936ed8e7736277a1031c9eee.
> Revert "chore(TCOMP-2617): CI: Component Runtime master job is not triggering builds on commits (#846)"

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/MappingUtils.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/MappingUtilsTest.java
https://jira.talendforge.org/browse/TCOMP-2626
> fix(TCOMP-2626): fix "null" literal in mapString

- bom/pom.xml
- container/container-core/src/main/java/org/talend/sdk/component/container/ContainerManager.java
- talend-component-maven-plugin/pom.xml
- talend-component-maven-plugin/src/it/web/README.md
https://jira.talendforge.org/browse/TCOMP-2607
This PR is a fix for previous PR #850
On 2 elements:
1. Revert the mistake removing distributionManagement in BOM
2. Improve the ID creation due to milestone
> chore(TCOMP-2607) New release workflow fix

- talend-component-maven-plugin/src/it/web/test/tck-bulk-api-test/tck_bulk_api_test.json
https://jira.talendforge.org/browse/TCOMP-2603
A typo in a file break one of the api test, it is fixed with this PR
Clean extre non json char
> feat(TCOMP-2603) fix the bulk api exception issue

- documentation/src/main/antora/modules/ROOT/pages/component-defining-custom-icon.adoc
https://jira.talendforge.org/browse/TCOMP-2470
> fix(TCOMP-2470): SVG / PNG documentation not complete

- documentation/src/main/antora/modules/ROOT/pages/studio-schema.adoc
discovering_schema_guess_schema action.
> fix(TCOMP-2454): Improve the documentation for

- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/service/IconResolver.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/front/ComponentResourceImplTest.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/service/IconResolverTest.java
https://jira.talendforge.org/browse/TCOMP-2679
> feat(TCOMP-2679): handle svg icons in studio

- component-tools/src/main/java/org/talend/sdk/component/tools/ComponentValidator.java
- component-tools/src/main/java/org/talend/sdk/component/tools/SvgValidator.java
- component-tools/src/test/java/org/talend/sdk/component/tools/ComponentValidatorTest.java
- component-tools/src/test/java/org/talend/sdk/component/tools/SvgValidatorTest.java
- component-tools/src/test/resources/SvgValidatorTest/valid40.svg
- component-tools/src/test/resources/SvgValidatorTest/viewboxsize40.svg
https://jira.talendforge.org/browse/TCOMP-2682
> feat(TCOMP-2682): update svg validator mojo

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2688
> fix(TCOMP-2688): Upgrade cxf to 3.5.8

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2687
> fix(TCOMP-2687): Upgrade tomcat to 9.0.87

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2687
> fix(TCOMP-2687): Upgrade tomcat to 9.0.87 backport to 1.38

- bom/pom.xml
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2692
> feat(TCOMP-2692): upgrade jackson to 2.16.0

- component-tools/src/main/java/org/talend/sdk/component/tools/SvgValidator.java
- component-tools/src/test/java/org/talend/sdk/component/tools/ComponentValidatorTest.java
- component-tools/src/test/java/org/talend/sdk/component/tools/SvgValidatorTest.java
https://jira.talendforge.org/browse/TCOMP-2693
> feat(TCOMP-2693): update svg validation mojo

- Jenkinsfile
https://jira.talendforge.org/browse/TCOMP-2696
> chore(TCOMP-2696): Move TCK daily master build earlier

- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRowStructVisitor.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/record/DiRowStructVisitorTest.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/record/VisitorsTest.java
> fix(TCOMP-2700): element schema for deep arrays

- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchema.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchemaTest.java
https://jira.talendforge.org/browse/TCOMP-2707
> fix(TCOMP-2707): correct workflow and exception throwing

- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/ValidateComponentMojo.java
https://jira.talendforge.org/browse/TCOMP-2697
> feat(TCOMP-2697): enable http client validation

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/xbean/registry/EnrichedPropertyEditorRegistry.java
https://jira.talendforge.org/browse/TCOMP-2567
> fix(TCOMP-2567): fix ZonedDateTime widget renderer

- component-runtime-beam/pom.xml
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/BeamProducerFinder.java
- component-runtime-testing/component-runtime-beam-junit/src/test/java/org/talend/sdk/component/junit/beam/ProducerFinderEnvironmentTest.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/junit5/environment/BeamEnvironmentsTest.java
https://jira.talendforge.org/browse/TCOMP-2741
Revert remove static modifier in BeamProducerFinder TCOMP-2339
> feat(TCOMP-2741): revert remove static modifier in beam producer finder

- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/cli/EnhancedCli.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/front/ConfigurationTypeResourceImpl.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/front/error/DefaultExceptionHandler.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/service/jcache/FrontCacheKeyGenerator.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/service/jcache/FrontCacheResolver.java
https://jira.talendforge.org/browse/TCOMP-2712
(cherry picked from commit 49477a9d2429b3f557322e9e8371c72bfcead36c)
> fix(TCOMP-2712):  fix create cache issue

- documentation/src/main/java/org/talend/runtime/documentation/Generator.java
https://jira.talendforge.org/browse/TCOMP-2755
> chore(TCOMP-2755): prevent milestones in changelog

- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchema.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/schema/TaCoKitGuessSchemaTest.java
Reverts Talend/component-runtime#888 
Superseded  by https://github.com/Talend/component-runtime/pull/902
> Revert "fix(TCOMP-2707): correct workflow and exception throwing"

- documentation/src/main/java/org/talend/runtime/documentation/Generator.java
https://jira.talendforge.org/browse/TCOMP-2759
> chore(TCOMP-2759): include milestones in changelog

- component-tools/src/main/java/org/talend/sdk/component/tools/ComponentValidator.java
https://jira.talendforge.org/browse/TCOMP-2766
> Item(TCOMP-2766): check svg with log.error

- component-tools/src/main/java/org/talend/sdk/component/tools/ComponentValidator.java
https://jira.talendforge.org/browse/TCOMP-2766
> Item(TCOMP-2766): check svg with log.error (#909)

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2765
> fix(TCOMP-2765):Update Tomcat to 9.0.93

- component-api/src/main/java/org/talend/sdk/component/api/configuration/action/Updatable.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/AbstractWidgetConverter.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/ObjectWidgetConverter.java
- component-form/component-form-core/src/test/java/org/talend/sdk/component/form/api/UiSpecServiceTest.java
- component-form/component-form-core/src/test/resources/update_after.json
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/reflect/parameterenricher/ActionParameterEnricherTest.java
https://jira.talendforge.org/browse/TCOMP-1989
> feat(TCOMP-1989):On PDesigner forms, Have button position not set to bottom when linked property is not displayed

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2770
> Item(TCOMP-2770): Upgrade cxf to 3.5.9

- .jenkins/jenkins_pod.yml
- .jenkins/scripts/asdf_install.sh
- .tool-versions
- Jenkinsfile
https://jira.talendforge.org/browse/TCOMP-2796
> chore(TCOMP-2796) evolve pod for maintenance 1.38

- Jenkinsfile
Revert CI fix and remove double pod (for java 17) blocking the CI start
https://jira.talendforge.org/browse/TCOMP-2796
> chore(TCOMP-2796) Fix CI

- container/container-core/src/main/java/org/talend/sdk/component/classloader/ConfigurableClassLoader.java
- container/container-core/src/test/java/org/talend/sdk/component/classloader/ConfigurableClassLoaderTest.java
https://jira.talendforge.org/browse/TCOMP-2798
> fix(TCOMP-2798): enable cacheable class loading

- Jenkinsfile
https://jira.talendforge.org/browse/TCOMP-2851
> chore(TCOMP-2851) Allow to select docker images to build on ci build 

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/internationalization/InternationalizationServiceFactory.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/asm/PluginGenerator.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/InternalizationServiceTest.java
- component-runtime-manager/src/test/java/org/talend/test/DataInput.java
- component-runtime-manager/src/test/java/org/talend/test/I18nService.java
- component-runtime-manager/src/test/resources/org/talend/test/Messages.properties
https://jira.talendforge.org/browse/TCOMP-2800
> fix(TCOMP-2800): use calling module classloader as secondary loader

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchema.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroWriterTest.java
* fix creation of empty avro records to much schema part with serialization part
https://jira.talendforge.org/browse/TCOMP-2827
> fix(TCOMP-2827): empty avro records

- pom.xml
https://jira.talendforge.org/browse/TCOMP-2861
> Item(TCOMP-2861): Upgrade avro to 1.11.4

- component-tools/src/test/java/org/talend/sdk/component/tools/SVG2PngTest.java
[QTDI-747](https://qlik-dev.atlassian.net/browse/QTDI-747)
[QTDI-747]: https://qlik-dev.atlassian.net/browse/QTDI-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(QTDI-747) Add junit coverage for svg2png

- talend-component-maven-plugin/pom.xml
- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/ClasspathMojoBase.java
* filter null value in case if dependency were empty in pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-840
> fix(QTDI-840): mvn npe

- component-runtime-testing/component-runtime-junit/pom.xml
- component-runtime-testing/component-runtime-junit/src/main/java/org/talend/sdk/component/maven/MavenDecrypter.java
- component-runtime-testing/component-runtime-junit/src/test/java/org/talend/sdk/component/maven/MavenDecrypterTest.java
- component-runtime-testing/component-runtime-junit/src/test/resources/maven/base/settings.xml
https://qlik-dev.atlassian.net/browse/QTDI-877
> chore(QTDI-877): support conf/setting.xml in MavenDecrypter

- .jenkins/scripts/trivy_build_tck.sh
- .jenkins/scripts/trivy_scan.sh
- .jenkins/scripts/trivy_upload.sh
- ci/Jenkinsfile-trivy
https://qlik-dev.atlassian.net/browse/QTDI-329
remove invalid line :  'apk add curl' because curl is on our image.
Move scripts to files. 
> fix(QTDI-329) fix trivy

- pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-886
> fix(QTDI-886): upgrade tomcat to 9.0.97

- ci/Jenkinsfile-release
https://qlik-dev.atlassian.net/browse/QTDI-867
After Milestone quit for tck, need to remove some security.
Also remove the BOM build.
> chore(QTDI-867) fix release job

- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/AvroRecordBuilderFactoryProvider.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/AvroRecordBuilderFactoryProviderTest.java
- component-runtime-impl/pom.xml
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/SchemaImplTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/SchemaWithoutSanitizeTest.java
https://qlik-dev.atlassian.net/browse/QTDI-114
> feat(QTDI-114): switch sanitize on schema

- pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-1025
> chore(QTDI-1025): upgrade commons-io to 2.18.0

- remote-engine-customizer/pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-1027
> chore[QTDI-1027]:Upgrade guava to 33.3.1-jre

- component-runtime-testing/component-runtime-http-junit/pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-1026
> chore(QTDI-1026):Upgrade netty to 4.1.115

- pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-1065
> chore(QTDI-1065): upgrade tomcat to 9.0.98

- sample-parent/sample-features/fixed-schema/README.md
https://qlik-dev.atlassian.net/browse/QTDI-1152
> chore(QTDI-1152): Improve @FixedSchema sample connector's readme.

- Jenkinsfile
- talend-component-maven-plugin/src/it/web/test/pom.xml
- talend-component-maven-plugin/src/it/web/test/tck-cache-api-test/pom.xml
- talend-component-maven-plugin/src/it/web/test/tck-cache-api-test/tck_cache_api_test.json
https://qlik-dev.atlassian.net/browse/QTDI-1188
> chore(QTDI-1188) add api test for undx branch

- Jenkinsfile
Fix jenkins file default java version to not overwrite systematically the tool version value.
https://qlik-dev.atlassian.net/browse/QTDI-1223
> chore(QTDI-1223): Fix jenkins file default java version

- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/service/jcache/FrontCacheResolverTest.java
> fix(QTDI-1188): fix unit test

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecord.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordTest.java
https://qlik-dev.atlassian.net/browse/QTDI-1279
> fix(QTDI-1279): Fix UTC timezone.

- .jenkins/jenkins_pod.yml
acatoire/QTDI-1293_increase_jenkins_pod_ram
https://qlik-dev.atlassian.net/browse/QTDI-1293
Stop using limits ressources definition
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
> ci(QTDI-1293): Increase jenkins pod ram

- component-runtime-testing/component-runtime-http-junit/pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-1301
> Upgrde netty to 4.119

- pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-1302
> Upgrde tomcat to 9.0.100

- Jenkinsfile
ci(QTDI-996): Fix script when no build before and bump the shared lib
https://qlik-dev.atlassian.net/browse/QTDI-996
> ci(QTDI-996): Fix release when no build before and no failure slack

- .jenkins/jenkins_pod.yml
chore(QTDI-1432): update mountPath for Jenkins M2 repository
https://qlik-dev.atlassian.net/browse/QTDI-1432
> chore(QTDI-1432): update mountPath for Jenkins M2 repository

- sample-parent/sample-features/checkpoint-runner/README.md
- sample-parent/sample-features/checkpoint-runner/src/main/java/org/talend/sdk/component/sample/feature/checkpoint/CheckpointInput.java
- sample-parent/sample-features/checkpoint-runner/src/main/java/org/talend/sdk/component/sample/feature/checkpoint/Cli.java
- sample-parent/sample-features/checkpoint-runner/src/main/java/org/talend/sdk/component/sample/feature/checkpoint/IncrementalSequenceInput.java
- sample-parent/sample-features/checkpoint-runner/src/main/resources/checkpoint-default.json
- sample-parent/sample-features/checkpoint-runner/src/main/resources/checkpoint-error.json
- sample-parent/sample-features/checkpoint-runner/src/main/resources/checkpoint-v1.json
- sample-parent/sample-features/checkpoint-runner/src/main/resources/org/talend/sdk/component/sample/feature/checkpoint/Messages.properties
> feat(QTID-675): Some changes in checkpoint sample.

- documentation/src/main/antora/modules/ROOT/pages/concept-processor-and-batch-processing.adoc
> https://qlik-dev.atlassian.net/browse/QTDI-1219  Add documentation for LastGroup annotation

- pom.xml
- sample-parent/sample-features/checkpoint-runner/pom.xml
- sample-parent/sample-features/checkpoint-runner/src/main/java/org/talend/sdk/component/sample/feature/checkpoint/Cli.java
- sample-parent/sample-features/checkpoint-runner/src/main/resources/org/talend/sdk/component/sample/feature/checkpoint/OptionDescriptions.properties
- sample-parent/sample-features/checkpoint-runner/suppressions.xml
> feat(QTDI-675): Checkpoint cli

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/chain/ChainedInput.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/checkpoint/CheckpointInputTest.java
- component-runtime-manager/src/test/java/org/talend/test/MapperWithCheckpoint.java
- component-runtime-manager/src/test/java/org/talend/test/StoreRecordInMemoryProcessor.java
https://qlik-dev.atlassian.net/browse/QTDI-1466
> fix(QTDI-1466): Fix chained input

- component-starter-server/src/build/GrabGradleWrapper.groovy
- component-tools/src/main/java/org/talend/sdk/component/tools/ComponentValidator.java
- gradle-talend-component/src/main/java/org/talend/sdk/component/gradle/ValidateTask.java
- pom.xml
* update icons validation
* bump gradle version to 6.9.4 it includes Java16 support backport, looks like it works with Java17
* fix NoMethodError for constructor creation
> fix(QTDI-1512): gradle build fix

- ci/Jenkinsfile-release
chose(QTDI-1527) Fix release job
https://qlik-dev.atlassian.net/browse/QTDI-1527
> chose(QTDI-1527) Fix release job

- component-server-parent/component-server-api/src/main/java/org/talend/sdk/component/server/api/CacheResource.java
- component-server-parent/component-server-model/src/main/java/org/talend/sdk/component/server/front/model/CacheClear.java
- component-server-parent/component-server/src/main/java/org/talend/sdk/component/server/service/jcache/FrontCacheResolver.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/service/jcache/FrontCacheResolverTest.java
https://qlik-dev.atlassian.net/browse/QTDI-1449
- https://github.com/Talend/component-runtime/pull/1035 (component-runtime)
- https://github.com/Talend/tdi-studio-se/pull/11053 (maintenance/8.0.2)
- https://github.com/Talend/tdi-studio-se/pull/11083 (master)
> feat(QTDI-1449): add CacheClear class

- reporting/pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-1561
> fix(QTDI-1561): fix-jetbrain-plugin-dep-in-reporting-module

- pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-1550
> chore(QTDI-1550): upgrade Tomcat to 9.0.104

- sample-parent/sample-connector/src/main/java/org/talend/sdk/component/test/connectors/input/TheInput1.java
- sample-parent/sample-connector/src/main/java/org/talend/sdk/component/test/connectors/input/TheMapper1.java
[QTDI-1669](https://qlik-dev.atlassian.net/browse/QTDI-1669)
[QTDI-1669]: https://qlik-dev.atlassian.net/browse/QTDI-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(QTDI-1669): sample with return variable

- component-starter-server/pom.xml
- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/configuration/StarterConfiguration.java
- images/component-starter-server-image/pom.xml
- images/pom.xml
> fix(QTDI-359): forbid all sources for CSP

- component-studio/pom.xml
- pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-1553
> chore(QTDI-1553): release-zl profile for studio modules

- pom.xml
> chore(QTDI-1827): remove tidy plugin

- component-starter-server/src/main/frontend/src/app/components/Help/Help.module.scss
* return original size of svg
* align the svg inside for better view (in the middle of the parent element)
* add a padding inside to have a space between icon and it's related element
> fix(QTDI-1016): missing pixel for Help button

- .jenkins/scripts/mvn_sonar_branch.sh
- .jenkins/scripts/mvn_sonar_pr.sh
https://qlik-dev.atlassian.net/browse/QTDI-1825
> feat(QTDI-1825): Switch Sonar instance to https://sonar.rnd-ci.cloud.talend.com

- component-server-parent/component-server/pom.xml
- component-starter-server/pom.xml
- pom.xml
> chore(QTDI-1861): bump version of git-commit-id

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
> fix(QTDI-1953): allow using container core classes
