- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SchemaSettingsCreator.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
adds Schema by default for every component on Basic view.
Side effect: it adds schema also to Dataset and Datastore (it can be fixed)
> feat(TCOMP-681): add dummy schema property

- component-studio-integration/src/main/java/org/talend/sdk/component/studio/ServerManager.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/TemplatesExtractor.java
- component-studio-integration/src/main/java/org/talend/sdk/component/studio/provider/TaCoKitComponentsProvider.java
* Extract guess schema javajets
* Implement methods required for guess schema in studio
Should work after https://github.com/Talend/tdi-studio-se/pull/1854 and https://github.com/Talend/tcommon-studio-se/pull/1369 are merged
> feat(TCOMP-683): Guess schema

- component-server/src/main/java/org/talend/sdk/component/server/front/ComponentResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/ConfigurationTypeResource.java
- component-server/src/main/java/org/talend/sdk/component/server/front/filter/message/MessageResponseFilter.java
- component-server/src/main/java/org/talend/sdk/component/server/front/model/ConfigTypeNode.java
- component-server/src/main/java/org/talend/sdk/component/server/service/ActionsService.java
Enriches ConfigTypeNode with ActionReferences
Implements ActionsService to be used by both ComponentResource and ConfigurationTypeResource
> feat(TCOMP-681): enrich ConfigurationType with ActionReference

- .gitignore
- component-kit.js/.babelrc
- component-kit.js/package-template.json
The released version of component-kit.js is es6
Means user needs to transpire dependencies
```
.../node_modules/component-kit.js/src/form-trigger.js
Module parse failed: Unexpected token (34:6)
You may need an appropriate loader to handle this file type.
|   return function onDefaultTrigger(event, { trigger, schema, properties, errors }) {
|     const services = {
|       ...defaultRegistry,
|       ...customRegistry
|     };
```
transpil in prepublish to es5
update main to lib/index.js
> fix(component-kit.js): update setup to transpile the lib

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/ComponentManager.java
`beam-sdks-java-core` classes are identified and loaded from the parent classloader by looking at the code location, and matching against the filename of the jar.
Some of our services use the sbt-native-packager which copies artifacts to a `lib/` directory and *renames* them by prefixing the group id, which doesn't work with the current logic.
Relax how the beam core jar is identified by looking at the jar file name with and without the prefixed group id.
> fix(TFD-6207): Relax beam core artifact identification by filename.

- gradle-talend-component/src/main/java/org/talend/sdk/component/gradle/TaCoKitPlugin.java
- Currently the Talend Gradle Component plugin lacks of the possibility to deploy the module components to the Studio.
- The task was already existed in the plugin, but was not registered. I just added this task so users can deploy from CLI.
> [TCOMP-1341] Add DeployInStudioTask in Gradle Plugin

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaBuilder.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaTest.java
When building Avro, the tacokit DATETIME is indistinguishable from a LONG.
Annotate the Avro schema with standard LogicalTypes.timestampMillis().
> fix(TFD-7165): Use LogicalTypes.timestampMillis() on DATETIME.

- component-tools/src/main/java/org/talend/sdk/component/tools/exec/CarMain.java
- Following the docs at https://talend.github.io/component-runtime/main/1.1.8/build-tools-maven.html#_generating_the_component_archive I found an issue when trying to install the component to a local maven repo by
```
java -jar mycomponent.car maven-deploy /path/to/.m2/repository
```
- Fix the wrong condition in CarMain.
> Fix wrong condition

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchema.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaTest.java
Follow-up to TFD-7165 / #361
The current assumption is that all Avro records are tagged with tacokit properties to determine the official tacokit type.  In some cases (such as reading directly from Avro, or using an intermediate processor that doesn't annotate or propagate tacokit types), this information is not available.
Normally the mapping is OK and transparent anyway, except for DateTime, which should fall back to the LogicalType provided by Avro.
Date, Time are not supported, just DateTime --> LogicalTypes.timestampMillis()
> fix(TFD-7292): Correctly interpret Avro LogicalType as tacokit type.

- component-form/component-form-model/src/main/java/org/talend/sdk/component/form/model/uischema/UiSchema.java
fix https://jira.talendforge.org/browse/TCOMP-1441
initialize the new instance of UISchema Parameter class with a key and a path before adding it to the list of parameters of the schema.
> fix(TCOMP-1441): init Parameter in the UISchema builder

- component-runtime-beam/src/test/java/org/talend/test/wrapped/JdbcSource.java
Changed the failback coder to fix a test that is breaking after some changes in upstream Beam.
R: @rmannibucau
> Change failback Coder for NativeWrappedIOTest.WorkAroundCoder to be JsonpJsonObjectCoder

- component-starter-server/src/main/java/org/talend/sdk/component/starter/server/front/ProjectResource.java
- component-tools/src/main/java/org/talend/sdk/component/tools/exec/CarMain.java
- talend-component-kit-intellij-plugin/src/main/java/org/talend/sdk/component/intellij/module/ProjectDownloader.java
There are some potential "Zip Slip" vulnerabilities in tcompe, when a zip file containing "../.." type entries can break out of the destination path when being extracted:
./component-runtime/component-tools/src/main/java/org/talend/sdk/component/tools/exec/CarMain.java
./component-runtime/talend-component-kit-intellij-plugin/src/main/java/org/talend/sdk/component/intellij/module/ProjectDownloader.java
./component-runtime/component-starter-server/src/main/java/org/talend/sdk/component/starter/server/front/ProjectResource.java
> TCOMP-1554 - Fix for potential "Zip Slip" vulnerabilites

- component-server-parent/component-server-vault-proxy/src/main/java/org/talend/sdk/component/runtime/server/vault/proxy/service/http/ClientSetup.java
Even for createUnsafeSSLContext I don't see any reason to use SSL in SSLContext.getInstance.
> Switch ClientSetup to use TLS instead of SSL

- pom.xml
We should update Apache CXF to 3.3.6 due to CVE-2020-1954:
http://cxf.apache.org/security-advisories.data/CVE-2020-1954.txt.asc?version=1&modificationDate=1585730169000&api=v2
> TCOMP-1692 - Update CXF to 3.3.6

- pom.xml
This task is to update BouncyCastle to 1.65. In some of the projects, we needed to ship a beta version of 1.65 due to a bug with Java 11 and TLS.
> TCOMP-1697 - Update BouncyCastle to 1.65

- pom.xml
This task is to update Log4j 2 to 2.13.2 due to the following CVE:
[CVE-2020-9488] Improper validation of certificate with host mismatch in Apache Log4j SMTP appender
https://seclists.org/oss-sec/2020/q2/72
> TCOMP-1703 - Update Log4j 2 to 2.13.2

- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/PropertiesConverter.java
- component-form/component-form-core/src/test/java/org/talend/sdk/component/form/internal/converter/impl/PropertiesConverterTest.java
UiSpecService injects a wrong property for suggestions and dynamic_values
See: https://jira.talendforge.org/browse/TCOMP-1698
> fix(TCOMP-1698): UiSpecService injects a wrong property

- component-runtime-testing/component-runtime-http-junit/pom.xml
- component-runtime-testing/component-runtime-http-junit/src/main/java/org/talend/sdk/component/junit/http/internal/impl/DefaultResponseLocatorCapturingHandler.java
- component-runtime-testing/component-runtime-http-junit/src/main/java/org/talend/sdk/component/junit/http/internal/impl/HandlerImpl.java
- component-runtime-testing/component-runtime-http-junit/src/main/java/org/talend/sdk/component/junit/http/internal/impl/PassthroughHandler.java
- component-runtime-testing/component-runtime-http-junit/src/main/java/org/talend/sdk/component/junit/http/internal/impl/ServingProxyHandler.java
https://jira.talendforge.org/browse/TCOMP-1852
No code change, tests already there
No change
The netty shade in http testing module uses an old netty version not supporting java 11 (take care netty 5 alpha is "pre" most of the v4 now).
* It enables to disable unsafe usage on java 11 (-Dorg.talend.__shade__.io.netty.noUnsafe=true) and therefore avoid java >= 11 illegal access errors/warnings
* It sets the system property to disable host name verification of java 11 http client (not always sufficient but best effort, worse case user has to set it in its system properties/pom)
> Upgrade netty to v4.1.58.Final and ensure default http testing module is java 11 friendly over ssl

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/visitor/ModelVisitor.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/visitor/visitor/ModelVisitorTest.java
- documentation/src/main/antora/modules/ROOT/pages/javajet-to-componentkit.adoc
Fix of After Variables Feature.
https://jira.talendforge.org/browse/TCOMP-1935
It adds validation of what types the connector-writer can use when defines After variables.
I think List-type is still a tricky one and maybe a backdoor for us. But at least it's supported by
https://github.com/Talend/studio-tools/blob/12808863466ad7adecc3e24efe9db8c5489fd825/org.talend.cloud.publisher/src/main/java/org/talend/core/model/metadata/types/JavaTypesManager.java
> fix(TCOMP-1935) after variables

- ci/Jenkinsfile-scan
We've now got more licenses, and microservices can use their own application, so you don't loose work like a sandbox when it expires !
If you need dedicated branch scanning, use the sandboxes for that instead.
**What is the problem this PR is trying to solve?**
SAST scans are performed in a sandbox that expires and loses work.
**What is the chosen solution to this problem?**
SAST scans are now automatically creating an application, based on the previous sandbox name.
**Please check if the PR fulfills these requirements**
**[ ] This PR introduces a breaking change**
> Security chore(): Switch SAST Scan from sandbox to dedicated Application

- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-api/src/main/java/org/talend/sdk/component/api/service/schema/Schema.java
- component-api/src/test/java/org/talend/sdk/component/api/record/SchemaTest.java
- component-api/src/test/java/org/talend/sdk/component/api/service/record/RecordBuilderFactoryTest.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/BaseProcessorFn.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecord.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchema.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaBuilder.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/KeysForAvroProperty.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/RecordCollectors.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/transform/RecordBranchMapper.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/coder/registry/SchemaRegistryCoderTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/JsonSchemaSerializationTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/RecordCollectorsTest.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordBuilderFactoryImpl.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordConverters.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordImpl.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/SchemaImpl.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/Schemas.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordConvertersTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/SchemaImplTest.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/RecordServiceImpl.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/RecordPointerImplTest.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/RecordServiceImplTest.java
- component-runtime-testing/component-runtime-beam-junit/src/main/java/org/talend/sdk/component/junit/beam/Data.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/front/beam/BeamActionSerializationTest.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRecordVisitor.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/record/DiRecordVisitorTest.java
https://jira.talendforge.org/browse/TCOMP-1923
(need to adapt unit test on some connectors that use directly SchemaImpl instead of RecordBuilderFactory (couhbase, azure, dynamoDB)
> TCOMP-1923 : metadata in records

- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-api/src/test/java/org/talend/sdk/component/api/record/SchemaTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/SchemaImplTest.java
https://jira.talendforge.org/browse/TCOMP-2019
Fix when call twice "withEntry(entry, XX)" with same entry.
> TCOMP-2019 : fix complete entry collision

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecord.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchema.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaCache.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaConverter.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaCacheTest.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaConverterTest.java
- component-runtime-impl/pom.xml
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/SchemaImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/SchemaImplTest.java
https://jira.talendforge.org/browse/TCOMP-2018
Optimize conversion of TCK Record to Avro Record by keep a cache of Schema conversion.
(Because, most of time, Records of a pipeline shared same schema)
> TCOMP-2018 : optimized Avro record conversion from TCK

- talend-component-maven-plugin/src/main/java/org/talend/sdk/component/maven/ComponentDependenciesBase.java
The build on `master` is broken.
Fix the build.
We should always build the javadoc (or never, but here I believe we need it).
Currently, it is only built on 4 modules (added manually in their poms) when not on `master`: 
* `component-api`
* `component-runtime-junit`
* `component-runtime-beam-junit`
* `component-runtime-http-junit`
The issue is that I haven't found why yet. 
The javadoc is built:
* [partially on dev branches](https://jenkins-connectors.datapwn.com/job/component-runtime/job/build/job/master__TDI-2102_fixCloudComponentsBuild/7/consoleFull)
* [fully on …
> fix(TCOMP-2102): Fix javadoc to repare build

- talend-component-maven-plugin/src/it/web/.jenkins/Jenkinsfile
To stop to use the old ssh credentials on the Jenkins instance
> Use https instead of ssh

- talend-component-maven-plugin/src/it/web/.jenkins/Jenkinsfile
chore(TCOMP-2161) Add a new publisher for TTO
https://jira.talendforge.org/browse/TCOMP-2161
Improve Jenkins report to be compatible with internals tools (TTO)
- Add a JUnit publisher on top of recordIssues 
- Use constants for test files and records path
> chore(TCOMP-2161) Add a new publisher for TTO

- Jenkinsfile
https://jira.talendforge.org/browse/TCOMP-2269
The Jenkins job missed JUnit result publishing.
Add JUnit publisher in the "always" step.
> chore(TCOMP-2269): Junit publisher fix 

- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/BeamProducerFinder.java
🐛  _Issues_:
* TDP functional bug: https://jira.talendforge.org/browse/TDP-11429
* TCOMP technical bug: https://jira.talendforge.org/browse/TCOMP-2241
🗒️  _Summary_:
Impossibility of using the "join" (also named "lookup") capability of TDP (in the ongoing "Runtime Convergence" project) when the joined Dataset is implemented using Beam APIs and not fully in TCK.
It's the case for the Datasets of these types (at least, there are probably more):
- Local file
- S3
- ...
💥 _Log_:
A log has been spotted in Livy
```
No translator known for org.apache.beam.repackaged.direct_java.runners.core.construction.SplittableParDo$PrimitiveBoundedRead
```
Explicitely run "Join" Beam pipeline in the application classloader (see below for full explanation)
First, it's important to talk about the fact that TCK …
> fix(TCOMP-2241): use Beam-aware classloader to run ProducerFinder pipeline

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
See https://jira.talendforge.org/browse/TDP-11601
When using the `RecordBuilder#updateEntryByName` method, the order of the entries is not preserved: the renamed entry is moved to the end of the entry list.
After analysis, this is caused by the fact that one do not update the inner `orderState` attribute which is responsible for this.
> fix(TDP-11601): preserve entries order when updating entry name

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
Backport of #655 to maintenance branch for TCK 1.50 (which will be used by TDP for EAP)
> chore(TDP-11601): backport entry name order fix to TCK 1.50

- Jenkinsfile
Sonar checks fail with "java.lang.NoClassDefFoundError: com/google/common/collect/LinkedListMultimap$1KeySetImpl"
https://jira.talendforge.org/browse/TDI-48973
Following SFT bump of Sonar in 9.6, builds are failing with:
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/LinkedListMultimap$1KeySetImpl
This is linked to a bug on 9.6 using Sonar cache.
It is fixed in 9.7.1, however there is another blocker for SFT to stay on version 9.6 for the time being.
> chore(TDI-48973): Fix Sonar NoClassDefFoundError

- documentation/src/main/antora/site-template.yml
Exclude non latest maintenance versions from antora documentation generation process. Followed recommandations from:
https://wiki.talend.com/pages/viewpage.action?spaceKey=rd&title=component-runtime+release+process#componentruntimereleaseprocess-Documentationstepisfailingduetoantoraexception
Documentation build is failing with Antora duplicate nav exception following 2 recent maintenance releases which were not excluded.
Exclude 1.38.6 and 1.38.7 from the list of versions for Antora.
https://jira.talendforge.org/browse/TCOMP-2331
> chore(TCOMP-2331): Fix Antora duplicate nav exception

- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRowStructVisitor.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/record/DiRowStructVisitorTest.java
https://jira.talendforge.org/browse/TCOMP-2371
https://jira.talendforge.org/browse/TCOMP-2371
> fix(TCOMP-2371): [TCK JDBC]: Studio dynamic column metadata info : isKey should follow runtime dynamic object, not the input component's studio schema

- .jenkins/jenkins_pod.yml
- .jenkins/scripts/asdf_install.sh
- .jenkins/scripts/package.sh
- .jenkins/scripts/post-release.sh
- .jenkins/scripts/release.sh
- .jenkins/scripts/veracode-sca.sh
- .tool-versions
- Jenkinsfile
- ci/Jenkinsfile-scan
- talend-component-maven-plugin/src/it/web/.jenkins/Jenkinsfile
https://jira.talendforge.org/browse/TCOMP-2367
Jenkins job edition to move to custom builder tsbi base image
As explained in the doc https://github.com/Talend/tsbi-images/tree/main/tsbi/custom-builder, This image is intended to be the only image used on CI and should contain everything needed to build our products and run our automation scripts.
- tools are now setups with asdf
- Pod config is now shared between build and scan` .jenkins/jenkins_pod.yml`
- rename veracode steps to uniformize with others projects
> feat(TCOMP-2367) phase out layerspector for build and scan scripts

- component-api/src/main/java/org/talend/sdk/component/api/configuration/dependency/ConnectorRef.java
- component-api/src/main/java/org/talend/sdk/component/api/configuration/dependency/ConnectorReference.java
- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/reflect/parameterenricher/DependencyParameterEnricher.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/reflect/parameterenricher/DependencyParameterEnricherTest.java
https://jira.talendforge.org/browse/TCOMP-2451
Deprecate ConnectorReference class, and introduce ConnectorRef annotation instead. It helps to use a custom structure when we want to add extra connector dependencies on a connector. It helps manage UI.
> feat(TCOMP-2451): rework connector dependencies reference

- component-runtime-manager/src/main/java/org/talend/sdk/component/runtime/manager/service/api/ComponentInstantiator.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/service/api/ComponentInstantiatorTest.java
* ComponentInstatiator looks for component name in all matched plugins not only in the first one
> fix(TCOMP-2468): look for a component across all plugins

- component-api/src/main/java/org/talend/sdk/component/api/record/SchemaProperty.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRecordVisitor.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/record/DiRecordVisitorTest.java
Reverts Talend/component-runtime#787
> Revert "fix(TCOMP-2374): DIRecordVisitor to fill Studio Dynamic object's column name by tck Schema.Entry.getName which must follow tck name rule"

- .jenkins/scripts/release.sh
- Jenkinsfile
Restore extraBuildParams in release script
https://jira.talendforge.org/browse/TCOMP-2554
The CI was using env var to pass args to the release script.
After CI evolution this env var was not accessible anymore, this PR restore the functionality using script parameter instead of env var.
Add parameter to release.sh
> feat(TCOMP-2554): Restore extraBuildParams in release script

- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRecordVisitor.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/record/DiRecordVisitorTest.java
https://jira.talendforge.org/browse/TCOMP-2565
https://jira.talendforge.org/browse/TCOMP-2565
> fix(TCOMP-2565): support origin type pass for studio dynamic type

- bom/pom.xml
- pom.xml
https://jira.talendforge.org/browse/TCOMP-2636
> fix(TCOMP-2636): Upgrade commons-compress to 1.26.0

- component-tools/src/main/java/org/talend/sdk/component/tools/exec/CarMain.java
- component-tools/src/test/java/org/talend/sdk/component/tools/exec/CarMainTest.java
https://jira.talendforge.org/browse/TCOMP-2631
> fix(TCOMP-2631): use URLDecoder.decode method

- ci/Jenkinsfile-scan
https://jira.talendforge.org/browse/TDI-51172
https://jira.talendforge.org/browse/TDI-51172
> fix(TDI-51172): [Security Scan]: remove Veracode SAST scan in all connector repository as we have now enabled GitHub Advanced Security

- component-runtime-testing/component-runtime-http-junit/pom.xml
- component-tools/src/main/java/org/talend/sdk/component/tools/validator/HttpValidator.java
- component-tools/src/test/java/org/talend/sdk/component/tools/validator/HttpClientValidatorTest.java
https://jira.talendforge.org/browse/TCOMP-2743
> item(TCOMP-2743): Add missing httpclient validator unit test

- component-api/src/main/java/org/talend/sdk/component/api/configuration/ui/widget/ReadOnly.java
- component-form/component-form-core/src/main/java/org/talend/sdk/component/form/internal/converter/impl/widget/AbstractWidgetConverter.java
- component-form/component-form-core/src/test/java/org/talend/sdk/component/form/internal/converter/impl/UiSchemaConverterTest.java
- component-runtime-manager/src/test/java/org/talend/sdk/component/runtime/manager/reflect/parameterenricher/UiParameterEnricherTest.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/front/ComponentResourceImplTest.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/front/ConfigurationTypeResourceImplTest.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/test/InitTestInfra.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/test/jdbc/JdbcConfig.java
- component-server-parent/component-server/src/test/java/org/talend/sdk/component/server/test/jdbc/JdbcDataStore.java
- documentation/src/main/antora/modules/ROOT/pages/_partials/generated_ui.adoc
https://jira.talendforge.org/browse/TCOMP-2744
> feat(TCOMP-2744): add @ReadOnly annotation

- component-tools/src/main/java/org/talend/sdk/component/tools/validator/ActionValidator.java
- component-tools/src/test/java/org/talend/sdk/component/tools/validator/ActionValidatorTest.java
https://qlik-dev.atlassian.net/browse/QTDI-875
> feat(QTDI-875): extend validation to object

- Jenkinsfile
chore(QTDI-740) Remove POST_LOGIN_SCRIPT
https://qlik-dev.atlassian.net/browse/QTDI-740
> chore(QTDI-740) Remove POST_LOGIN_SCRIPT

- component-api/src/main/java/org/talend/sdk/component/api/record/Schema.java
- component-api/src/main/java/org/talend/sdk/component/api/record/SchemaCompanionUtil.java
- component-api/src/test/java/org/talend/sdk/component/api/record/SchemaCompanionUtilTest.java
- component-api/src/test/java/org/talend/sdk/component/api/record/SchemaTest.java
- component-api/src/test/java/org/talend/sdk/component/api/service/record/RecordBuilderFactoryTest.java
- component-api/src/test/java/org/talend/sdk/component/api/test/MockEntry.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/BaseProcessorFn.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecord.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/spi/record/AvroSchemaBuilder.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/transform/RecordBranchFilter.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/transform/RecordBranchMapper.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/transform/RecordBranchUnwrapper.java
- component-runtime-beam/src/main/java/org/talend/sdk/component/runtime/beam/transform/ViewsMappingTransform.java
- component-runtime-beam/src/test/java/org/talend/sdk/component/runtime/beam/spi/record/AvroRecordTest.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordImpl.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/SchemaImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderFactoryImplTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/SchemaCompanionUtilTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/SchemaImplTest.java
- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRowStructVisitor.java
- singer-parent/component-kitap/pom.xml
> fix(QTDI-679): schema collision with Cyrillic names

- .jenkins/settings.xml
- Jenkinsfile
- component-studio/component-runtime-di/pom.xml
- component-studio/pom.xml
- pom.xml
- talend-component-maven-plugin/pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-1553
> chore(QTDI-1553): migrate from osshr to central

- component-runtime-testing/component-runtime-junit/pom.xml
- documentation/pom.xml
- pom.xml
- singer-parent/component-kitap/pom.xml
> chore(QTDI-1826): unblock CodeQL

- component-starter-server/src/main/frontend/src/app/components/Mapper/Mapper.js
> fix(QTDI-845): starter-toolkit saves state

- component-studio/component-runtime-di/src/main/java/org/talend/sdk/component/runtime/di/record/DiRowStructVisitor.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/record/DiRowStructVisitorTest.java
- component-studio/component-runtime-di/src/test/java/org/talend/sdk/component/runtime/di/record/VisitorsTest.java
* replace it with the null
* set original value for inferschema
> fix(QTDI-1856): remove empty raw name for list

- component-starter-server/pom.xml
- component-tools-webapp/pom.xml
- component-tools/pom.xml
- documentation/pom.xml
- documentation/src/main/frontend/package-template.json
- pom.xml
- talend-component-maven-plugin/pom.xml
* improve bottom javadoc header
* disable javadoc doclint
> chore(QTDI-1047): reduce logs size

- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/MappingUtils.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/MappingUtilsTest.java
https://qlik-dev.atlassian.net/browse/QTDI-1942
> fix(QTDI-1942): Support negative timestamp in MappingUtils#mapString.

- container/container-core/src/main/java/org/talend/sdk/component/container/ContainerManager.java
https://qlik-dev.atlassian.net/browse/QTDI-1963
> fix(QTDI-1963): fix windows path for rootRepo

- component-api/src/main/java/org/talend/sdk/component/api/record/Record.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/MappingUtils.java
- component-runtime-impl/src/main/java/org/talend/sdk/component/runtime/record/RecordImpl.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/MappingUtilsTest.java
- component-runtime-impl/src/test/java/org/talend/sdk/component/runtime/record/RecordBuilderImplTest.java
- pom.xml
https://qlik-dev.atlassian.net/browse/QTDI-2023
Maybe don't squash before merge.
> chore(QTDI-2023): Backports 1.85.0 to 1.84.2
